### ISSUE TITLE
Needle editor confused by identically-named needles in different folders

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#1072]
In Fedora's distri we have several cases where we have identically named needles in different folders, e.g. `needles/gnome/desktop_no_notifications.json` and `needles/kde/desktop_no_notifications.json` . This really seems to confuse the needle editor: it shows both needles with their correct match %ages in its needle select dropdowns, but whichever one you pick it shows the same tags, and it doesn't seem to auto-generate the correct match areas at all even if you pick the needle that matched nearly perfectly, it just shows what looks like a default '100x100 top-left corner' match area. Also, if you play with the 'Take image from' dropdown, whichever of the two needles you pick, it'll show the same screenshot (which is the screenshot from one of those two needles - it never shows the screenshot from the other needle).

**Comment by okurz** [comment]
So this is a feature request for support of needles with the same names linked to the previous feature request about nested needle directories.

**Comment by AdamWill** [comment]
Well, they seem to mostly work fine already. It's only the interactive editor I've noticed getting confused. (And *possibly* needle un-registration).

**Comment by coolo** [comment]
please move this over to progress.oo if it's any important. we plan work there

**Comment by okurz** [comment]
recorded in https://progress.opensuse.org/issues/18484
