### ISSUE TITLE
UI improvements in jobs templates

### ISSUE THREAD

**Issue by pevik** [os-autoinst/openQA#1100]
Jobs templates (/admin/job_templates/1) deserves to be improved. 
* Update page after change or have some notification about change. When I add or delete item, it's handled via ajax, but view doesn't update. It would help to have some notification that change was done or update view and have link for undo. Now I have to refresh page to have view updated (and have to know that I need to do it.
* dropdown with thest suites isn't filtered, so I can add item which is already there and I get nice DBI exception :-).
* Is there a link for /admin/job_templates/1 (maybe it's somewhere I don't see it)? If not, I'd like to have it probably in "Logged as ..." menu.
* '+' could be bigger (to help better clicking).

PS: sorry to put more issues into one place and not putting it to http://progress.opensuse.org (I consider the problem as not openSUSE specific).

**Comment by coolo** [comment]
if it's opensuse specific or not doesn't matter. progress.opensuse.org is our task tracker. Please use it

**Comment by pevik** [comment]
OK, sorry. Reported as https://progress.opensuse.org/issues/15612.
DB Exception is already reported as https://progress.opensuse.org/issues/14964.
