### ISSUE TITLE
Red Hat Bugzilla identifier inconsistency: `rh` vs `brc`

### ISSUE THREAD

**Issue by Conan-Kudo** [os-autoinst/openQA#1151]
According to [openSUSE's list of abbreviations](https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines#Current_set_of_abbreviations) and [Open Build Service reference list](https://github.com/openSUSE/open-build-service/blob/master/docs/api/api/issue_trackers.xml), the Red Hat Bugzilla tracker identifier is supposed to be `rh`. However, it looks like it's defined as `brc` with commit e39e9227a8b289e0028b04c9872966406fc4e198.

Is there some way here we can resolve the inconsistency here? If indeed `brc` is preferred, then can we have this supported elsewhere? Or, if `rh` is preferred, then can we fix this and switch openQA to support this instead?

**Comment by okurz** [comment]
https://github.com/os-autoinst/openQA/pull/1083 introduced that originally and it was @AdamWill from redhat which included that.

**Comment by AdamWill** [comment]
I picked 'brc' to follow the obvious convention of all the existing ones. The abbreviation most commonly used by RH/Fedora people is 'rhbz' (or 'RHBZ'), but that didn't really fit in. I've never really seen 'rh' used as an identifier for 'Red Hat Bugzilla', it's only used for "Red Hat".

**Comment by coolo** [comment]
the build service uses what SUSE picked - while openQA uses what RH picked. So I don't see a problem there
