### ISSUE TITLE
All image resources at http://open.qa/documentation/ are broken

### ISSUE THREAD

**Issue by FlorianHeigl** [os-autoinst/openQA#1179]
Hi,

all the images are missing if one uses your main project site?

**Comment by foursixnine** [comment]
@FlorianHeigl Thanks for the report, I submitted a pr that should fix that. Please note that there's still some plumbing to be done :) There are aso some broken links. 

The PDF version is more suitable I would say, also the api documentation which can be found at http://open.qa/api/testapi has no images :)

**Comment by FlorianHeigl** [comment]
Hey, thanks!

I'll check again for the PDF version, didn't see it when I looked.
PDF is also my favorite for digging into new tools. :-)
