### ISSUE TITLE
worker permission denied creating /var/lib/openqa/pool/<instance>

### ISSUE THREAD

**Issue by michelmno** [os-autoinst/openQA#1197]
trying to manually start a worker as  per command documented in (1), the command failed as reported in (2)
there is no problem if worker started as an openqa-worker service (3)

(1) https://github.com/os-autoinst/openQA/blob/master/docs/Installing.asciidoc#run-workers
(2) Permission denied error:
```
# sudo -u _openqa-worker /usr/share/openqa/script/worker --instance 5
mkdir /var/lib/openqa/pool/5: Permission denied at /usr/share/openqa/script/../lib/OpenQA/Worker/Pool.pm line 31.
```
```
$ls -ltra /var/lib/openqa/pool            
total 0
drwxr-xr-x 1 root           root   8 Dec  7 19:29 .
drwxr-xr-x 1 root           root 102 Dec  8 05:41 ..
drwxr-xr-x 1 _openqa-worker root  14 Jan 12 17:51 4
drwxr-xr-x 1 _openqa-worker root  14 Jan 12 17:51 1
drwxr-xr-x 1 _openqa-worker root  14 Jan 12 18:19 3
drwxr-xr-x 1 _openqa-worker root  14 Jan 12 18:20 2
```
(3)
```
systemctl start openqa-worker@5
```

**Comment by Martchus** [comment]
When executing `sudo -u _openqa-worker /usr/share/openqa/script/worker --instance 5` the pool directory must already exist for the obvious reason `/var/lib/openqa/pool`  is owned by root and not by _openqa-worker.

The reason starting via systemctl works is the `ExecStartPre=/usr/bin/install -d -m 0755 -o _openqa-worker /var/lib/openqa/pool/%i` in the service file.

I will update the documentation.

**Comment by coolo** [comment]
did you?

**Comment by Martchus** [comment]
Yes: https://github.com/os-autoinst/openQA/commit/cfd233c90a52d85ca8ae825f1d2e12ab2aa01f4e
