### ISSUE TITLE
Installation - require an old version of "perl-Mojolicious-Plugin-AssetPack"

### ISSUE THREAD

**Issue by wnereiz** [os-autoinst/openQA#1226]
Add following repository in Leap 42.2:
[obs://devel:openQA/openSUSE_Leap_42.2](obs://devel:openQA/openSUSE_Leap_42.2)
[obs://devel:openQA:Leap:42.2/openSUSE_Leap_42.2](obs://devel:openQA:Leap:42.2/openSUSE_Leap_42.2)

The package "perl-Mojolicious-Plugin-AssetPack" version is **1.39,** but openQA-4.4.1486546788.30fde28 require **1.38,** which is can not be found.

**Comment by coolo** [comment]
this is hardly an issue with the code. Please use the mailing list for temporary issues like that
