### ISSUE TITLE
needle-editor: when adding more than one tag, there is no line break between them

### ISSUE THREAD

**Issue by Soulofdestiny** [os-autoinst/openQA#1227]
browser was in maximised mode:
![needle_edit](https://cloud.githubusercontent.com/assets/3983634/22918544/142d4e28-f28b-11e6-975c-c7cdefac257e.png)

**Comment by Soulofdestiny** [comment]
@Martchus probably for you ;)

**Comment by coolo** [comment]
please use progress.oo for openqa issues
