### ISSUE TITLE
Saving HDD image fails

### ISSUE THREAD

**Issue by vahidn83** [os-autoinst/openQA#1289]
I created a test case for one of my golden image OS (SLES based) and I'm trying to save the qemu HDD after finishing the installation and testing of the GI. However, I always get the following error (eventhough the OS shuts down successfully):
`ERROR: Machine not shut down when uploading disks!`

All the tests pass successfully and there's no other error. I set the KEEPHDDS to 1 in the Machines variables and use the following to launch my test:

`/usr/share/openqa/script/client jobs post DISTRI=GI VERSION=1 ISO=SLE-GI-OEM-DVD-x86_64-1.0.0.install.iso ARCH=x86_64 TEST=Host_test INSTALLONLY=1 SUPPORT_SERVER_GENERATOR=1 PUBLISH_HDD_1=host.qcow2`

**Comment by okurz** [comment]
take a look into https://openqa.opensuse.org/tests/381649# which is an example of an openSUSE test saving the generated qcow file. The machine should be shutdown explicitly before trying to save it.

**Comment by coolo** [comment]
but this is not a support forum. If you have problems, use a mailing list. e.g. opensuse-factory@opensuse.org

**Comment by vahidn83** [comment]
@okurz That's pretty much what I did for my tests. But, thanks for the help.
@coolo I understand that it's not a support forum, but since my test is similar to the standard opensuse test and I still get the failure error, I thought, it might be related to a bug. Maybe, my setup or host machine is different.
