### ISSUE TITLE
Interactive mode and "Stop waitforneedle" doesn't work

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/openQA#185]
I have updated to `openQA-4.1423751463.9d5dfbc-50.1.noarch` and "Stop waitforneedle" button stopped working (OpenQA doesn't stop when I click it). Also, although I am in interactive mode, immediately after `assert_screen` fails, it runs `post_fail_hook`.

When I searched through logs, I have noticed that clicking this button sends `POST` with wrong `workerid`:

    "POST /api/v1/workers/TODO/commands HTTP/1.1" 404 1032 "https://localhost/tests/10"

Searching through commits, I have found this: https://github.com/os-autoinst/openQA/commit/f0226cecb9e2a519be32bfcfbca81ddcf3f0a368#diff-89341987f897939f67f1f3120f797566L74 so this seems like regression error.

**Comment by coolo** [comment]
yeah. We actually tagged 4.0 for guys like you - but I will take a look

**Comment by garretraziel** [comment]
OK, thanks. It would be great to have RPMs to install. Maybe create something like stable repo?

**Comment by coolo** [comment]
http://software.opensuse.org/download.html?project=devel%3AopenQA%3Astable&package=openQA

**Comment by garretraziel** [comment]
Ok, I didn't know about that, perfect.

**Comment by coolo** [comment]
you won't be able to go back though with your database :)

**Comment by coolo** [comment]
please test the patch

**Comment by garretraziel** [comment]
I'm sorry, but we've moved our server to stable version since yesterday, so I am not able to test it at the moment.

**Comment by coolo** [comment]
even better

**Comment by coolo** [comment]
one problem less to worry about for me then :)
