### ISSUE TITLE
Web front end can't find files for tests

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#209]
I've just set up a test deployment of Fedora's openQA set up on a local system. It's mostly working, but all the features which rely on openQA being able to find files in the `testresults` directory don't seem to be working:

* I don't get a live log or live view while the tests are running
* I don't get a list of result files for a finished test
* I don't see thumbnails for each test step on a finished test (but I do see screenshots when I enter an individual test step)

Comparing to our production deployment where all this stuff works, I see what looks to be a significant difference. On our production deployment, the breadcrumb trail looks something like this:

openQA > Test results > fedora-rawhide-server-x86_64-Build22_Alpha_TC7-server_simple_encrypted

(i.e., whatever's considered the 'test name' for that display does not include the test number). But on my deployment it looks like this:

openQA > Test results > 00000011-fedora-rawhide-server-x86_64-Build22_Alpha_TC7-server_firewall_disabled

The test number *is* included, there.

however, for *both* deployments, the `testresults` subdirectory names have the test number in them. On my deployment I have:

`/var/lib/openqa/testresults/00000011-fedora-rawhide-server-x86_64-Build22_Alpha_TC7-server_firewall_disabled`

and on the working deployment there is:

`/var/lib/openqa/testresults/00000081-fedora-rawhide-server-x86_64-Build22_Alpha_TC7-server_simple_encrypted`

So I think there's probably some kind of mismatch somewhere and the server's probably looking for the files in `/var/lib/openqa/testresults/00000011-00000011-fedora-rawhide-server-x86_64-Build22_Alpha_TC7-server_firewall_disabled` or something like that, and that's why it can't find them? But I'm no perl expert and have no experience with Mojolicious, so I haven't been able to pin down exactly where the problem is, unfortunately.

**Comment by AdamWill** [comment]
Sorry, completely forgot an important bit of information. The *broken* deployment is running openQA-4.1425060466.5a5218e-162.1.noarch . The *working* deployment is running openQA-4.1423751463.9d5dfbc-49.1.noarch .

**Comment by AdamWill** [comment]
Sure enough, if I do this:

openqa:/var/lib/openqa/testresults # ln -s 00000011-fedora-rawhide-server-x86_64-Build22_Alpha_TC7-server_firewall_disabled fedora-rawhide-server-x86_64-Build22_Alpha_TC7-server_firewall_disabled

then the thumbnails and 'result files' show up.

**Comment by AdamWill** [comment]
OH HEY LOOKIT ME I KNOW PERL NOW

**Comment by coolo** [comment]
make a pull request please - your fix looks good

**Comment by coolo** [comment]
merged, thx - for reference, we're tracking bugs *we* find at https://progress.opensuse.org/projects/openqav3/issues - feel free to fix more of them :)

(even though I thought Fedora openQA uses the 4.0 version - git master is slightly in a flux)

**Comment by AdamWill** [comment]
"feel free to fix more of them :)"

with my awesome perl skillz, ok ;)

The deployment I hit this on is just one I set up for my own development / learning OpenQA purposes, but I think both I and Josef when he was setting up the 'production' deployment just followed the installation guide with the obvious modification for 13.2: https://github.com/os-autoinst/openQA/blob/master/docs/Installing.asciidoc

so we did:

    zypper ar -f obs://devel:openQA/openSUSE_13.2 openQA
    zypper ar -f obs://devel:openQA:13.1/openSUSE_13.2 openQA-perl-modules
    zypper in openQA

if that's not a good idea right now, and there's a stable repo that folks should use instead, maybe the doc can be updated? thanks!

(my instance is up at openqa.happyassassin.net if you want to watch me futz around, btw.)

**Comment by coolo** [comment]
we try hard not to break master - but our test coverage is not so great. It should work, but our releases get clearly more testing

**Comment by AdamWill** [comment]
clearly what you need is some sort of automated test framework. ;)

**Comment by coolo** [comment]
if you know a good one that is actually tested, let me know :)
