### ISSUE TITLE
How to begin a test on openQA WebUI?

### ISSUE THREAD

**Issue by choldrim** [os-autoinst/openQA#265]
I have done all installation work as the REAME guid, and add the test suites to job templates, when I start the worker manually, but it seems nothing has happened.
```shell
sudo /usr/share/openqa/script/worker --instance 1 --apikey D80EDAB499F5XXXX --apisecret 26D316CD06XXXXXX --verbose
```
output:
```shell
## adding timer register_worker 0
## removing timer register_worker
registering worker ...
new worker id is 1...
## adding timer setup_websocket 0
## removing timer setup_websocket
WEBSOCKET ws://localhost/api/v1/workers/1/ws
## adding timer ws_keepalive 5
## adding timer check_job 0
## removing timer check_job
checking for job ...
POST http://localhost/api/v1/workers/1/grab_job?backend=qemu&cpu_arch=x86_64&mem_max=3847&cpu_opmode=32-bit,+64-bit&instance=1&host=choldrim-pc
```
I add the job on openQA WebUI follow:
https://github.com/os-autoinst/openQA/blob/master/docs/GettingStarted.asciidoc#using-job-templates-to-automate-jobs-creation

it seems the backend can't find the jobs difined on WebUI, I get this trouble for a long time ;( ,  who would do me a favor, thanks.

**Comment by aaannz** [comment]
You probably didn't add any iso to the test, see https://github.com/os-autoinst/openQA/blob/master/docs/GettingStarted.asciidoc#adding-a-new-iso-to-test

**Comment by choldrim** [comment]
Yes, I have add an iso to factory dir, and excute:
```shell
$  /usr/share/openqa/script/client isos post \                             
         ISO=deepin_2014.2_amd64.iso \                
         DISTRI=deepin \
         VERSION=Factory \
         FLAVOR=NET \
         ARCH=x86_64 \
         BUILD=0053
```
and I get this output:
```shell
{ count => 0, ids => [] }
```

**Comment by nilxam** [comment]
looks like your instance missing job template for your test, you have to create one for it.

**Comment by aaannz** [comment]
And check if you don't have typos in variables DISTRI, VERSION, FLAVOR and ARCH and your product definition. Maybe it can't match the product.
You need to have count > 0

**Comment by lnussel** [comment]
openqa webui debug output will also print a line if it can't find matching products

**Comment by choldrim** [comment]
the worker can find the jobs after running this cmd:
```shell
/var/lib/openqa/tests/opensuse/templates
```
I think I may be wrong when creating the jobs on the web ui.
thanks for all of your reply.  :)

Would I ask another question?
Is "/usr/share/openqa/script/client" the only way to add a job from "Job templates" to the "scheduled jobs"?

**Comment by choldrim** [comment]
and... is there any interface to delete the scheduled jobs?

**Comment by lnussel** [comment]
Choldrim schrieb:
> Would I ask another question? Is "/usr/share/openqa/script/client" the
> only way to add a job from "Job templates" to the "scheduled jobs"?

It's the only command line client we ship. Of course you could write
your own tool to talk to the REST API.

**Comment by lnussel** [comment]
Choldrim schrieb:
> and... is there any interface to delete the scheduled jobs?

No but you can cancel them.
