### ISSUE TITLE
dump_templates does not include the now-required `group_name`

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#291]
Since https://github.com/os-autoinst/openQA/commit/3f32a11f254e17ad523e4b5be55a5cb65fce88db it seems some `group_name` field is required in templates files to be loaded by `load_templates`, but `dump_templates` does not seem to include it - so you can't load a dumped templates file any more.

**Comment by AdamWill** [comment]
ah, looks like https://github.com/os-autoinst/openQA/pull/282 fixes this.

**Comment by coolo** [comment]
exactly
