### ISSUE TITLE
Unable to log in after installation

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/openQA#320]
I don't know whether it's related to #72 (but I don't have any Unicode character in my name), but after I installed OpenQA, I can not log in the first time - after I approve login from OpenID, it shows uniraptor vomiting rainbow.

`/var/log/openqa` shows:

    [Wed Apr  1 12:29:43 2015] [error] Can't locate object method "params" via package "Mojo::Parameters" at /usr/share/openqa/script/../lib/OpenQA/Controller/Session.pm line 127. 

I am using Fedora as OpenID provider (https://id.fedoraproject.org/). Complete redirect url is:

`https://localhost/response?oic.time=1427885467-58af4a2a435d16ecca1d&openid.assoc_handle={HMAC-SHA1}{551bcda7}{qGmiRA%3D%3D}&openid.ax.count.email=1&openid.ax.count.firstname=0&openid.ax.count.fullname=1&openid.ax.count.lastname=0&openid.ax.count.nickname=1&openid.ax.mode=fetch_response&openid.ax.type.email=http%3A%2F%2Fschema.openid.net%2Fcontact%2Femail&openid.ax.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ax.type.fullname=http%3A%2F%2Faxschema.org%2FnamePerson&openid.ax.type.lastname=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ax.type.nickname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffriendly&openid.ax.value.email.1=rajcze%40gmail.com&openid.ax.value.fullname.1=Project+Coconut&openid.ax.value.nickname.1=coconut&openid.claimed_id=http%3A%2F%2Fcoconut.id.fedoraproject.org%2F&openid.identity=http%3A%2F%2Fcoconut.id.fedoraproject.org%2F&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.ax=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.op_endpoint=https%3A%2F%2Fid.fedoraproject.org%2Fopenid%2F&openid.pape.auth_level.nist=2&openid.pape.auth_level.ns.nist=http%3A%2F%2Fcsrc.nist.gov%2Fpublications%2Fnistpubs%2F800-63%2FSP800-63V1_0_2.pdf&openid.pape.auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&openid.pape.auth_time=2015-04-01T10%3A51%3A16Z&openid.response_nonce=2015-04-01T10%3A51%3A19Z0YncuX&openid.return_to=https%3A%2F%2Flocalhost%2Fresponse%3Foic.time%3D1427885467-58af4a2a435d16ecca1d&openid.sig=%2Bnm8zJ8MHyA%2FWDrVw93IWUJa13M%3D&openid.signed=assoc_handle%2Cax.count.email%2Cax.count.firstname%2Cax.count.fullname%2Cax.count.lastname%2Cax.count.nickname%2Cax.mode%2Cax.type.email%2Cax.type.firstname%2Cax.type.fullname%2Cax.type.lastname%2Cax.type.nickname%2Cax.value.email.1%2Cax.value.fullname.1%2Cax.value.nickname.1%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cns.ax%2Cns.pape%2Cns.sreg%2Cop_endpoint%2Cpape.auth_level.nist%2Cpape.auth_level.ns.nist%2Cpape.auth_policies%2Cpape.auth_time%2Cresponse_nonce%2Creturn_to%2Csigned%2Csreg.email%2Csreg.fullname%2Csreg.nickname&openid.sreg.email=rajcze%40gmail.com&openid.sreg.fullname=Project+Coconut&openid.sreg.nickname=coconut`

**Comment by aaannz** [comment]
Do you have uptodate openqa installation? This might be related to Mojolicious6, I was fixing similar error.

**Comment by garretraziel** [comment]
I am using stable release from stable repo and whatever Mojolicious is in openQA-Perl-libs.

**Comment by aaannz** [comment]
Ok, I see the problem. It is indeed Mojo6 issue. The problem is that stable package is not building after update due to missing dependencies so it's still on last good 4.0 version.

**Comment by aaannz** [comment]
Fixed the project, packages should be ready in a moment and try to upgrade to 4.1. Fix for Mojo6 is included.

**Comment by garretraziel** [comment]
I also had to add http://download.opensuse.org/repositories/devel:/languages:/perl/openSUSE_13.2/ repo for some Perl libs, but it works now. Thanks.
