### ISSUE TITLE
NOIMAGES is not evaluated

### ISSUE THREAD

**Issue by k0da** [os-autoinst/openQA#324]
Despite medium type says NOIMAGES=1, start_install test fails.
https://openqa.opensuse.org/tests/55390

**Comment by coolo** [comment]
And you're sure it said NOIMAGES already at the moment the ISO was scheduled?

**Comment by k0da** [comment]
Yes, as restarted job doesn't have it either

**Comment by coolo** [comment]
restart just clones the current settings, it doesn't reschedule the ISO

**Comment by coolo** [comment]
according to the database NOIMAGES was added 04-01 while the ISO is from Mar 31 17:06

**Comment by coolo** [comment]
https://openqa.opensuse.org/tests/55512 has it now - your bug is none
