### ISSUE TITLE
script/fetchneedles got "No such file or directory"

### ISSUE THREAD

**Issue by zxdvd** [os-autoinst/openQA#338]
I got **/usr/share/openqa/script/fetchneedles: line 58: cd: /var/lib/openqa/tests/opensuse: No such file or directory** when running **/usr/share/openqa/script/fetchneedles**.
I added following line after line 57 to avoid this problem:
    
    [ -d "$dir/$dist" ] || mkdir "$dir/$dist"

**Comment by okurz** [comment]
PR https://github.com/os-autoinst/openQA/pull/469
