### ISSUE TITLE
is it possible to have iso file name in "Download iso" url ?

### ISSUE THREAD

**Issue by michelmno** [os-autoinst/openQA#369]
Hello there, 
I have a question regarding the "Download iso" url (1) that is presented in a test result page (2)
Would it be possible to have the url to contain the name of the iso file (Tumbleweed-BE-DVD-ppc64-Snapshot20150516-Media.iso) rather than a number (3498) ?
This would ease the copy/paste of the url to then wget for test on another machine. Today I have to manually find the iso file name and then do a rename after wget operation.

(1) https://openqa.opensuse.org/tests/63224/asset/3498
(2) https://openqa.opensuse.org/tests/63224

**Comment by coolo** [comment]
https://github.com/os-autoinst/openQA/pull/471
