### ISSUE TITLE
Missing certs in openQA GUI with apache

### ISSUE THREAD

**Issue by jeremiah** [os-autoinst/openQA#3708]
When I run this command;

`$ podman run --rm -it registry.opensuse.org/devel/openqa/containers15.2/openqa_webui:latest`

I get this result;

```
AH00526: Syntax error on line 18 of /etc/apache2/vhosts.d/openqa-ssl.conf:
SSLCertificateFile: file '/etc/apache2/ssl.crt/server.crt' does not exist or is empty
```

**Comment by ilausuch** [comment]
Yes, this is something commented on our meetings. The idea is that the user provides these certs. There is a very easy way to do that. Maybe you would like to see a demo to deploy openqa_webui https://asciinema.org/a/388812 and see the script to do that

**Comment by okurz** [comment]
@ilausuch what we can consider is using by default the certificates that perl-Mojolicious provides, e.g. in

```
/usr/lib/perl5/vendor_perl/5.26.1/Mojo/IOLoop/resources/server.crt
/usr/lib/perl5/vendor_perl/5.26.1/Mojo/IOLoop/resources/server.key
```

**Comment by shenlebantongying** [comment]
I got an SSL cert related problem too. I used the `openqa-bootstrap-container`..............

```
openqa1:/ # openqa-clone-job --from https://openqa.opensuse.org 1623342 --skip-chained-deps
failed to get job '1623342':  SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
```

**Comment by okurz** [comment]
Ok, but this is a different error add certificates can be found. Please report a new issue

**Comment by Martchus** [comment]
At this point, the [docker-compose based setup](https://open.qa/docs/#_setup_openqa_with_opensuse_based_images_and_docker_compose) contains a default certificate.
