### ISSUE TITLE
script/client does not accept variables containing '='

### ISSUE THREAD

**Issue by psladek** [os-autoinst/openQA#376]
when running a test from commandline, e.g.

/usr/share/openqa/script/client jobs post DISTRI=sle VERSION=12 ISO=SLE-12-Server-DVD-x86_64-GM-DVD1.iso ... MYPARAM='name=value'

returns : 
ERROR: 403 - Forbidden
{ error => "Not authorized" }

somehow, '=' is incorrectly parsed and causes and invalid error message (all is well if '=' is not present).

**Comment by nilxam** [comment]
hmm...can you give me a complete command with params? I tried below in my local instance and worked.

/usr/share/openqa/script/client isos post iso=openSUSE-Staging-Core-Staging2-DVD-x86_64-Build396.3-Media.iso DISTRI=opensuse VERSION=Staging-Core FLAVOR=Staging2-DVD ARCH=x86_64 Build=396.3 MYPARAM='HAHA=blabla'
{ count => 4, ids => [146 .. 149] }

**Comment by psladek** [comment]
sorry for late answer - hm, strange, your commandline example also fails for me... have you tried the 'jobs post' also (not isos)? Otherwise the failure happens in my first example, even if you simply use it as it is, without '...'

**Comment by nilxam** [comment]
your first example looks missing TEST var as it is requires anyway.

without TEST var:
tigercity:/var/lib/openqa/factory/iso # /usr/share/openqa/script/client jobs post iso=SLE-12-SP1-Server-DVD-x86_64-Build2477-Media1.iso DISTRI=sle VERSION=12 MYPARAM='name=value'ERROR: 400 - Bad Request
{
  error => "DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::SQLite::st execute failed: NOT NULL constraint failed: jobs.test [for Statement \"INSERT INTO jobs ( t_created, t_updated, test) VALUES ( ?, ?, ? )\"] at /usr/share/openqa/script/../lib/OpenQA/Scheduler.pm line 197\n",
}

with TEST var:
tigercity:/var/lib/openqa/factory/iso # /usr/share/openqa/script/client jobs post iso=SLE-12-SP1-Server-DVD-x86_64-Build2477-Media1.iso DISTRI=sle VERSION=12 MYPARAM='name=value' TEST=gnome
{ id => 187 }
tigercity:/var/lib/openqa/factory/iso # /usr/share/openqa/script/client jobs/187
{
  job => {
           assets     => { iso => ["SLE-12-SP1-Server-DVD-x86_64-Build2477-Media1.iso"] },
           clone_id   => 188,
           group_id   => undef,
           id         => 187,
           name       => "sle-12-gnome",
           priority   => 50,
           result     => "incomplete",
           retry_avbl => 3,
           settings   => {
                           DISTRI  => "sle",
                           ISO     => "SLE-12-SP1-Server-DVD-x86_64-Build2477-Media1.iso",
                           MYPARAM => "name=value",
                           NAME    => "00000187-sle-12-gnome",
                           TEST    => "gnome",
                           VERSION => 12,
                         },
           state      => "done",
           t_finished => "2015-06-26T07:33:09",
           t_started  => "2015-06-26T07:33:07",
           test       => "gnome",
           worker_id  => 0,
         },
}

can you test with TEST var and give a feedback does it the culprit?

**Comment by psladek** [comment]
just tested the above command and found that the openqa test machine where it was run was not updated for some time (~since late may). After update, params with '=' works well, and behaves same as in the output above.
Seems the problem has been somehow resolved in the meantime..  :)

**Comment by nilxam** [comment]
ok, close then :)
