### ISSUE TITLE
support mojo8 for a bit longer?

### ISSUE THREAD

**Issue by okurz** [os-autoinst/openQA#3892]
Ah, well, this leaves me in a bit of an awkward spot by dropping support for Mojo 8. Fedora 34 released with Mojo 8. So now I either have to do a major, incompatible version bump of Mojo in Fedora 34, or introduce some kind of new "mojolicious9" package, or run our openQA instance on Rawhide, or leave it outdated (or revert this patch) for the next six months. None of those feel like fantastic options...:(

_Originally posted by @AdamWill in https://github.com/os-autoinst/openQA/issues/3830#issuecomment-834803586_

**Comment by okurz** [comment]
can we do something about this?

**Comment by AdamWill** [comment]
I have to go back and look at it again, but I think when I was first looking at this, it should at least be possible to conditionalize the routes on Mojo version. A bit ugly, but plausible.

I am currently looking through things that depend on Mojo in Fedora and seeing how things look for Mojo 9 compatibility, but it would be rather against Fedora policies to do a major release bump in a stable Fedora even if all the deps were portable. In theory we care about third parties, who might not appreciate whole chunks of Mojo's API disappearing in a stable update.

Then of course, we'd have to not introduce any other Mojo 9-isms for the next ~6 months until I could bump our servers to F35.

If I'd known this was happening before F34 Final freeze I could've stuffed Mojo 9 into it, but I didn't :(

**Comment by okurz** [comment]
fixed by https://github.com/os-autoinst/openQA/pull/3898
