### ISSUE TITLE
random clones shown in test result

### ISSUE THREAD

**Issue by lnussel** [os-autoinst/openQA#3919]
Was looking at results of TW snapshot 20210524
https://openqa.opensuse.org/tests/overview?distri=microos&distri=opensuse&version=Tumbleweed&build=20210524&groupid=1

in the list create_hdd_gnome lead me to https://openqa.opensuse.org/tests/1757810

That is not the original test though. it has CASEDIR=https://github.com/sofiasyria/os-autoinst-distri-opensuse#iscsi so someone cloned the job with custom settings, ie the results shown in the overview are misleading.

There is also no obvious indication that the test was modified or even a clone.

**Comment by okurz** [comment]
Interesting. The job says "Scheduled product: opensuse-Tumbleweed-DVD-x86_64-20210524" so it really looks like a "production test". I agree that the test should either not show up this way at all or at least be explicit.

 @sofiasyria can you help me understand how you triggered the mentioned job? Did you do it manually or as part of the product schedule in https://openqa.opensuse.org/group_overview/1 ?

**Comment by sofiasyria** [comment]
I did isos post for child tests, so create_hdd_gnome was triggered with casedir as well. I will delete the non-original create_hdd_jobs to avoid confusion. I tried initially _SKIP_CHAINED_DEPS but it's a multi-machine test I'm working on so that was not working for me. Sorry if that caused you any problems

**Comment by Martchus** [comment]
This could have been avoided by setting `_GROUP=0` (see https://open.qa/docs/#_trigger_new_tests_by_modifying_settings_from_existing_test_runs).

**Comment by okurz** [comment]
@sofiasyria no worries. Thanks for the context.

@Martchus right, not a *problem* per se but a dangerous API route with no better alternative for multi-machine tests. This is something we should improve but I don't know how.
