### ISSUE TITLE
Consider moving to Fork-Awesome or another free font

### ISSUE THREAD

**Issue by phil-hands** [os-autoinst/openQA#4158]
Hi!

While packaging OpenQA for Debian I noticed that OpenQA now uses Font-Awesome v5: os-autoinst/openQA@89a7480671bb326078ba122774f2b81ec7b285a6

I presume that the reason for that change was simply to update to the latest and greatest, but unfortunately it comes at the cost of making OpenQA impossible to build from source.

As of v5, FontAwesome switched to a proprietary build system and it is no longer possible to build the icons. Of course, this was done silently and I am sure you were not aware of this when migrating.

We were in contact with Font-Awesome developers (see [Debian Bug #902981](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902981#76)) and they responded clearly (and it seems that nothing's changed since):

    the first question to get out of the way is: “Will Font Awesome open source their build tool?”

    And the answer is no for the time being.

This makes it impossible, for example, for Font-Awesome v5 to be included in Debian.

The community reacted to this at the time, and the [Fork-Awesome project](https://forkaweso.me) was created, which is a fork of Font-Awesome v4, from back when the build system was still available.

BTW Fork-Awesome has a v5 compatibility layer (see: ForkAwesome/Fork-Awesome#112) which was introduced when the same issue was noticed in [Syncthing]( https://github.com/syncthing/syncthing/pull/5237).  I don't know if the compatibility layer is really necessary for OpenQA's usage, or whether it would be cleaner to revert the change linked above and just use Fork-Awesome directly.

FWIW I have tested the compatibility layer with OpenQA, and to my (somewhat unschooled eye) it seems to work well.

Would OpenQA consider migrating to Fork-Awesome?

Cheers, Phil.

**Comment by coolo** [comment]
Would you even have noticed if we copied font awesome into our assets folder and put a CC-BY-4.0 license next to it? I assume CC-BY-4.0 works for debian.

**Comment by kraih** [comment]
Mojolicious has files bundled under`CC-BY-SA` license (which is more strict than `CC-BY`), so it should be fine for Debian.

**Comment by Martchus** [comment]
We're not using Font-Awesome's build system but just downloading their released files. However, it would likely be possible to simply adjust the URLs in `assetpack.def` (and then follow https://open.qa/docs/#update-asset-cache).

**Comment by phil-hands** [comment]
> Would you even have noticed if we copied font awesome into our assets folder and put a CC-BY-4.0 license next to it? I assume CC-BY-4.0 works for debian.

I don't know, it perhaps depends upon whether lintian would have alerted me to the embedded copy.

I noticed this because I'm trying to eliminate all the downloads that are being done at build time for the Debian packaging, and then noticed the odd version numbering of fonts-font-awesome in Debian (ver:  5.0.10+really4.7.0~dfsg-4.1), which lead me eventually to the fact that font-awesome v5 is non-free as far as DFSG is concerned, because it is not buildable from source, and that one possible solution to that is to use fork-awesome, which seems to have been found acceptable by at least one other upstream, as mentioned.

Do you have some objection to using fork-awesome instead?

**Comment by okurz** [comment]
> Do you have some objection to using fork-awesome instead?
> 
> Update: Anyway, I see that Martchus is busy fixing it, so that question is hopefully moot.

Yes, we currently plan to use Fork-Awesome unless we find a solution by only downloading ready-made assets from CDN in a non-obtrusive way that would fit your requirements.

**Comment by Martchus** [comment]
My PR to migrate to ForkAwesome has been merged.
