### ISSUE TITLE
Showing more than 500 test results not working with sqlite

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/openQA#421]
When listing all test results (by going to `http://openqa/tests`), when there is 500 results or more, OpenQA crashes with sqlite database. In log, there is:

    [Thu Aug  6 08:23:23 2015] [error] DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: 
     DBD::SQLite::db prepare_cached failed: too many SQL variables [for Statement "SELECT 
     me.child_job_id, me.parent_job_id, me.dependency FROM job_dependencies me WHERE ( ( 
     child_job_id IN ( ?, ...,  ? ) OR parent_job_id IN ( ?, ...,  ? ) ) )"]
    at /usr/share/openqa/script/../lib/OpenQA/Controller/Test.pm line 122

It's actually caused by code [here](https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/WebAPI/Controller/Test.pm#L47) and [here](https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/WebAPI/Controller/Test.pm#L92). 500 results is queried from db, but it's used twice in SQL query and according to [this](http://www.sqlite.org/limits.html), maximum number of host parameters in a single SQL statement is 999. Editing those two lines to limit query to 499 results works.

**Comment by aaannz** [comment]
Are you sure it's those lines? I think it's [this line](https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/WebAPI/Controller/Test.pm#L117) where `@ids` are 500 ids long and used twice in one query.
But anyway, bug is there, I'll take a look and try to come up with something.

**Comment by garretraziel** [comment]
I am not sure, I have just edited 500 to 499 and it worked :-). It may be what you have found.

**Comment by aaannz** [comment]
Take a look at #423. I removed the long query for dependencies and streamlined it a little.

**Comment by garretraziel** [comment]
I'm sorry, but we are running openQA 4.1-3.1 and it seems that actual version of Test.pm is incompatible with our version, so I cannot test it. I guess that I could backport changes somehow. I can provide you with our database, though.

**Comment by aaannz** [comment]
This should be solved in master. Feel free to reopen if not
