### ISSUE TITLE
undocumented requirement: DISTRI variable must be lowercase 

### ISSUE THREAD

**Issue by dcermak** [os-autoinst/openQA#4333]
I stumbled over the issue that I created a product via the API with `DISTRI` being `SLE`. This caused really weird scheduling issues, since for (to me) no apparent reason openQA wasn't scheduling any jobs for that product. I believe that this is caused `DISTRI` being lowercased in various places, e.g.:
https://github.com/os-autoinst/openQA/blob/13b6255025ea1d8cdc2032e36c43f5e38546d63b/lib/OpenQA/Schema/Result/ScheduledProducts.pm#L183

This causes an implicit requirement on `DISTRI` to be lowercased, which is not documented anywhere and really, really hard to figure out unless you peek into the source code.

**Comment by dcermak** [comment]
> Hm, maybe I'm missing something here, but what I meant is that all operations in openQA writing that field to the database make sure to lowercase it.

I am not 100% sure about this, because I have managed to somehow run into the edge case where openQA was looking for the `DISTRI` `SLE` but it was saved as `sle` due to the lowercasing.

**Comment by dcermak** [comment]
Shall we document this?

**Comment by okurz** [comment]
Yes, that would be good. If you find a good place where to add it in docs please go ahead. I don't have a good suggestion handy right now.
