### ISSUE TITLE
Move 'find latest jobs for build' logic out of `overview()`, make it available for API query

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#436]
There's this thing the `overview()` function in `lib/OpenQA/WebAPI/Controller/Test.pm` does:

    my %seen;
    while (my $job = $jobs->next) {
        my $settings = $job->settings_hash;
        my $testname = $settings->{NAME};
        my $test     = $job->test;
        my $flavor   = $settings->{FLAVOR} || 'sweet';
        my $arch     = $settings->{ARCH} || 'noarch';
        my $key      = "$test-$flavor-$arch-" . $settings->{MACHINE};
        next if $seen{$key}++;

that's really not only useful right there. We in fact need to do that exact same filter when generating a report for the tests run on a given compose in Fedora. So I had to effectively duplicate it in openQA-python-client: https://github.com/os-autoinst/openQA-python-client/commit/0bffa10a1a8655693cad2fd477542e1ed33bcf13

Obviously it's bad to have two bits of code for the same thing. What would be good is if this logic could be moved somewhere else and made available via the query API, as well as being used for this one specific web UI view.

I tried to do this by moving the filtering into `query_jobs()`, but then realized that doesn't really work at all because `query_jobs()` returns a DBIC `ResultSet` and you can't really filter those like this. It doesn't seem like a good idea to suddenly switch `query_jobs()` to return an array of `Result`s, or something. So, I figure the way to go would be to add a little function that you can feed the `query_jobs()` `ResultSet` to and it will give you the filtered array of `Result`s, and then the `overview()` function could use it and we could also wire it into the query API somehow.

I'm willing to work on this, but I'm just not entirely sure where the helper function should go, or whether there's a better design for this. Any thoughts?

**Comment by coolo** [comment]
I'd put a function in OpenQA::Schema::ResultSet::Jobs that does this filtering and returns said array.

**Comment by okurz** [comment]
@AdamWill is this fixed with #472 or do you think about other additions?
Lately I have been experimenting with an "openQA client" myself to better understand what he UI and/or the web API currently offers. What I was actually looking for is not the "latest job for build" but "last finished job for build", for now doing webscraping and looking for the progress bar component of "in progress" eq 0. Another use case would be to search for incomplete builds, e.g. where an architecture is missing from a multi-arch build. Can this be accomplished with the current version of the 'latest job' query?

**Comment by AdamWill** [comment]
Well, what you could do is first get a `ResultSet` of jobs with your conditions applied - all finished jobs for the build, for e.g. - then run it through `latest_jobs`. You should be able to do this with the web API too, I think, with something like `&state=done&latest=true` - the way the code's set up, what winds up happening is `query_jobs` will get called with the 'state' param, then `latest_jobs` is run on the ResultSet.

**Comment by okurz** [comment]
I see, thx.

**Comment by okurz** [comment]
@AdamWill as asked before, can you close this issue?
