### ISSUE TITLE
`Can't call method "websockets"` error message when displaying workers in admin

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/openQA#438]
I've just installed openQA from repository and when I try to list all workers in admin, it shows dinosaur and in `/var/log/openqa` is:

```
[Fri Oct  2 13:26:21 2015] [error] Can't call method "websockets" on an undefined value at /usr/share/openqa/script/../lib/OpenQA/Schema/Result/Workers.pm line 123.
118: }
119: 
120: sub connected {
121:     my ($self) = @_;
122:     my $ipc = OpenQA::IPC->ipc;
123:     return $ipc->websockets('ws_is_worker_connected', $self->id) ? 1 : 0;
124: }
125: 
126: sub info {
127:     my ($self) = @_;
128: 
```

I have openQA-4.1443110314.cc82053-697.4.noarch and openQA-worker-4.1443110314.cc82053-697.4.noarch packages installed.

**Comment by aaannz** [comment]
How are you starting openQA? Using systemd service or script/openqa? Under what user?

**Comment by garretraziel** [comment]
I'm starting openQA with:

    rcapache2 start && /usr/share/openqa/script/openqa daemon -m production --proxy

under root user.

**Comment by aaannz** [comment]
Ok, that probably explains it.
Since enabling preforking openQA now consists of 3 processes. openqa-webui, openqa-scheduler, openqa-websockets. As IPC DBus is used. DBus policy shipped with openqa is specified only for `geekotest` user (see `/etc/dbus-1/system.d/org.opensuse.openqa.conf`).

So either use systemd service to start it or start scheduler and websockets before openqa webui/api:
```bash
/usr/share/openqa/script/openqa-scheduler &
/usr/share/openqa/script/openqa-websockets &
rcapache2 start && /usr/share/openqa/script/openqa daemon -m production --proxy
```

additionally you can use `prefork` instead of `daemon` as openqa option to run webui in multiple processes in case you need to handle higher traffic (more workers, visitors)

**Comment by garretraziel** [comment]
The reason we are running it like this is that we run openQA in Docker (where you have to run things directly, because you don't have any init system). But thanks, I'll try the second solution.

**Comment by AdamWill** [comment]
@garretraziel we definitely want to use the 'prefork' approach - it should stop the periodic 5xx errors we get when hitting the API when the server is busy, or at least seriously reduce them.

**Comment by garretraziel** [comment]
I still can't get it to work. The thing is, Docker container is like chroot or jail, it doesn't have init system (= systemd) running. Running Web UI in Docker gives me:

```
Uncaught exception from user code:
	org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
	Net::DBus::Binding::Bus::new("Net::DBus::Binding::Bus", "type", 1) called at /usr/lib/perl5/vendor_perl/5.20.1/x86_64-linux-thread-multi/Net/DBus.pm line 178
	Net::DBus::system("Net::DBus") called at /usr/lib/perl5/vendor_perl/5.20.1/x86_64-linux-thread-multi/Net/DBus.pm line 153
	Net::DBus::find("Net::DBus", "nomainloop", 0) called at /usr/share/openqa/script/../lib/OpenQA/IPC.pm line 48
	OpenQA::IPC::new("OpenQA::IPC") called at /usr/share/openqa/script/../lib/OpenQA/IPC.pm line 59
	OpenQA::IPC::ipc("OpenQA::IPC") called at /usr/share/openqa/script/../lib/OpenQA/Scheduler.pm line 38
	OpenQA::Scheduler::new("OpenQA::Scheduler") called at /usr/share/openqa/script/../lib/OpenQA/Scheduler.pm line 30
	OpenQA::Scheduler::run() called at /usr/share/openqa/script/openqa-scheduler line 27
Uncaught exception from user code:
	org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
	Net::DBus::Binding::Bus::new("Net::DBus::Binding::Bus", "type", 1) called at /usr/lib/perl5/vendor_perl/5.20.1/x86_64-linux-thread-multi/Net/DBus.pm line 178
	Net::DBus::system("Net::DBus") called at /usr/lib/perl5/vendor_perl/5.20.1/x86_64-linux-thread-multi/Net/DBus.pm line 153
	Net::DBus::find("Net::DBus", "nomainloop", 1) called at /usr/share/openqa/script/../lib/OpenQA/IPC.pm line 48
	OpenQA::IPC::new("OpenQA::IPC", Mojo::Reactor::Poll=HASH(0x344a3a0)) called at /usr/share/openqa/script/../lib/OpenQA/IPC.pm line 59
	OpenQA::IPC::ipc("OpenQA::IPC", Mojo::Reactor::Poll=HASH(0x344a3a0)) called at /usr/share/openqa/script/../lib/OpenQA/WebSockets.pm line 38
	OpenQA::WebSockets::new("OpenQA::WebSockets", Mojo::Reactor::Poll=HASH(0x344a3a0)) called at /usr/share/openqa/script/../lib/OpenQA/WebSockets.pm line 28
	OpenQA::WebSockets::run() called at /usr/share/openqa/script/openqa-websockets line 32
```
I've been trying to start dbus with `dbus-launch` but without success.

**Comment by aaannz** [comment]
I think `dbus-launch`starts user session, try `dbus-daemon --system --fork` to spawn system bus. 
But you can start init process in docker, can't you? :) Btw. I personally use `systemd-nspawn` containers for openQA (WebUI/API+Scheduler+WebSockets).
Or you can use `DBUS_STARTER_BUS_TYPE=session` environmental variable to force openQA to use session bus.

**Comment by garretraziel** [comment]
`dbus-daemon --system --fork` method worked (I had to create directory `/run/dbus`), but still, clicking on "workers" in admin interface gives me unicorn T-Rex and `/var/log/openqa` shows:

    [Tue Oct  6 07:40:51 2015] [error] Modification of non-creatable array value attempted, subscript -1 at /usr/lib/perl5/vendor_perl/5.20.1/Mojo/Exception.pm line 94.

**Comment by aaannz** [comment]
Do you have updated dockerfile to share?

**Comment by garretraziel** [comment]
All our docker files are here: https://bitbucket.org/rajcze/openqa_fedora_tools/src/c8c9b10cdfff82670f15a574aa2c8e09455c57e6/docker/?at=feature/docker_webui
`webui/` contains files and Dockerfile for building Docker WebUI container.

**Comment by AdamWill** [comment]
Well, I know why this is, and it's not an openQA bug: it's simply because the `run_openqa.sh` in the web UI container runs all the services as root, but the dbus policy only allows geekotest to own the DBus interfaces. root is not all-powerful for DBus, root's just treated like any other user - there has to be a rule allowing things run as root to do stuff, if there isn't, they can't.

So the fix for this is simply to run the processes as geekotest, not as root. @garretraziel , I'll commit the fix to the branch in `openqa_fedora_tools` .

**Comment by garretraziel** [comment]
Ok, so for future reference: you need to create necessary dbus directory `/var/dbus`, you need to start dbus by running `dbus-daemon --system --fork`, you need to run all necessary daemons under correct user (`geekotest`). So the correct way how to run it without systemd is:

```
mkdir -p /run/dbus
dbus-daemon --system --fork
su geekotest -c '/usr/share/openqa/script/openqa-scheduler &'
su geekotest -c '/usr/share/openqa/script/openqa-websockets &'
su geekotest -c '/usr/share/openqa/script/openqa gru -m production run &'
rcapache2 start && su geekotest -c '/usr/share/openqa/script/openqa prefork -m production --proxy'
```
