### ISSUE TITLE
Jobs do not run if perl::EV is installed

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#450]
While getting openQA running on Fedora, I ran into a problem. Jobs will not run if perl::EV is installed. They'll be scheduled, but while the worker is starting up you get this message: `EV does not work with ithreads`. Per [Mojo FAQ](http://mojolicio.us/perldoc/Mojolicious/Guides/FAQ#What-does-the-error-EV-does-not-work-with-ithreads-mean), it seems that the EV reactor and interpreter threads are basically incompatible. openQA doesn't use threads, but os-autoinst does.

I tried sticking `$ENV{"MOJO_REACTOR"} = "Mojo::Reactor::Poll";` at the top of `isotovideo`, but that didn't seem to do the trick. Perhaps it needs to go in openQA somewhere, maybe `Worker.pm`?

I can deal with this somewhat in downstream by dropping the Fedora Mojolicious package's (bogus) hard requirement of EV and making the openQA package conflict with it, but it seems like something that might also/better be addressed upstream. Mojo in SUSE doesn't *depend* on EV, but it doesn't *conflict* with it, and any time you happen to install it, your openQA is gonna stop working.

**Comment by coolo** [comment]
worker.pm only makes sense if openQA would use threads. I'll install EV and we'll see :)
