### ISSUE TITLE
Replace DEPENDENCIES.txt with cpanfile

### ISSUE THREAD

**Issue by frioux** [os-autoinst/openQA#453]
`cpanfile` is a more standard alternative to your current DEPENDENCIES.txt thing.  If you migrate to cpanfile you can install deps with just `cpanm --installdeps .`.

Here's an example of it in action: https://github.com/frioux/DBIx-Class-Candy/blob/master/cpanfile

If you need help let me know and I'll see if I can come up with some time to send a PR.

**Comment by okurz** [comment]
PR always welcome, I'd gess :-)

**Comment by coolo** [comment]
I must say I like it - didn't know about its existance ;)
