### ISSUE TITLE
Allow the WebUI to display different resolutions for screenshots and videos

### ISSUE THREAD

**Issue by sdclarke** [os-autoinst/openQA#4691]
After https://github.com/os-autoinst/os-autoinst/pull/2070, os-autoinst can now be passed parameters to control the resolution of the VM display. When using a resolution other than the default it does not display correctly in the WebUI due to hardcoding of the default.

This should be adjusted such that the resolution of screenshots/needles and the live view can match the actual dimensions of the display.

**Comment by okurz** [comment]
Reopening as likely still valid. Also I created https://progress.opensuse.org/issues/117136 to prevent the stale bot to close issues which are still valid.

**Comment by Martchus** [comment]
Yes, looking at the changes from that PR I also think this issue can be closed. So I'm closing it now but feel free to re-open it if something is missing after all.
