### ISSUE TITLE
setting links are not rendered properly in case of multi-urls

### ISSUE THREAD

**Issue by b10n1k** [os-autoinst/openQA#4740]
seems that when settings which has
1. link reference (http,ftp, etc)
2. is a list instead of a single value (ex INCIDENT_REPO	http://download.suse.de/ibs/SUSE:/Maintenance:/24944/SUSE_Updates_SLE-Product-HPC_15-SP2-LTSS_x86_64,http://download.suse.de/ibs/SUSE:/Maintenance:/24944/SUSE_Updates_SLE-Product-SLES_15-SP2-LTSS_x86_64)

Notice that the values are seperated by a comma above.

Then the url doesnt render a corresponding link to each url. 

To reproduce: https://openqa.suse.de/tests/9102040#settings and click on the url variable of INCIDENT_REPO.

Results: a NOT_FOUND page with url https://download.suse.de/ibs/SUSE:/Maintenance:/24944/SUSE_Updates_SLE-Product-HPC_15-SP2-LTSS_x86_64,http://download.suse.de/ibs/SUSE:/Maintenance:/24944/SUSE_Updates_SLE-Product-SLES_15-SP2-LTSS_x86_64

expected:
two links in the above example
one for `SUSE_Updates_SLE-Product-HPC_15-SP2-LTSS_x86_64` and one for `SUSE_Updates_SLE-Product-SLES_15-SP2-LTSS_x86_64`

**Comment by Martchus** [comment]
Fixed by #4741.
