### ISSUE TITLE
QEMUVGA=virtio does not work in latest contains

### ISSUE THREAD

**Issue by ssssam** [os-autoinst/openQA#4795]
The `openqa_worker` container no longer supports QEMU `-vga virtio` option. So tests on openqa.gnome.org have been failing with `qemu-system-x86_64: Virtio VGA not available`.

The GNOME OS images do not work with the standard QEMU vga backend. (That may be fixable, but i don't know how much effort).

It seems like virtio support wasn't deliberately removed, rather that the following snippet in [`scripts/openqa_bootstrap`](https://github.com/os-autoinst/openQA/blob/master/script/openqa-bootstrap#L36) stopped working:

```
# this was split into a separate package on newer dist versions - so install it if available
if zypper -n search -x qemu-hw-display-virtio-gpu-pci ; then
    zypper -n install --no-recommends qemu-hw-display-virtio-gpu qemu-hw-display-virtio-gpu-pci
fi
```

**Comment by Martchus** [comment]
Ok, so this is simply about the bootstrapping script then. Judging by https://build.opensuse.org/package/binaries/openSUSE:Factory/qemu/standard the package is still there under that name on Tumbleweed. Which distribution did you run the bootstrapping script on? It would also be good to have any logs of the invocation of the bootstrapping script which didn't install the required package.

And have you double checked whether the package is really missing in your installation (and that installing it manually helped)? Just to be sure the issue hasn't a whole different cause after all.

**Comment by ssssam** [comment]
Hello, thanks for the quick response!

We are using the OpenQA container images from registry.opensuse.org, specifically  devel/openqa/containers15.3/openqa_worker. Is there a way to get build logs for that container without re-running the build locally myself? (will do that tomorrow if needed)

I have verified that the package is missing and installing it fixes the issue.

**Comment by ssssam** [comment]
I tried a local `cd openQA/container/worker; docker build .` and got a new error, seems that it's building against Leap 15.4 but hasn't been fully updated for that , or something ...

```
STEP 1/8: FROM opensuse/leap:15.4
...
Retrieving: os-autoinst-4.6.1662465492.44da018-lp154.1383.1.x86_64.rpm [not found]
File './x86_64/os-autoinst-4.6.1662465492.44da018-lp154.1383.1.x86_64.rpm' not found on medium 'http://download.opensuse.org/repositories/devel:openQA/15.4'
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
```

So I'm not sure how to work on solving this locally right now.

**Comment by Martchus** [comment]
Looks like container builds for Leap 15.3 are completely disabled now. So don't use `devel/openqa/containers15.3/openqa_worker`. Better use `devel/openqa/containers15.4/openqa_worker`. The latest build log is available on https://build.opensuse.org/package/live_build_log/devel:openQA/openQA_container_worker/containers15.4/x86_64 but I'm not sure whether you have access to view this page (maybe you need an account on OBS at least).

However, if you use the container image, I suppose that means you then do *not* use the bootstrapping script. The container image is built via https://github.com/os-autoinst/openQA/blob/master/container/worker/Dockerfile (which is downloaded by OBS from GitHub). Maybe that `Dockerfile` needs further tweaking for your use-case. Note that our container images do not generally contain all the packages required for all conceivable use-cases, though. (os-autoinst has many backends, not just QEMU. Likely one does not want to have all dependencies of all features of all backends in one container as it might get a little big.)

**Comment by ssssam** [comment]
Thanks for the help, I've now opened a PR to update the Dockerfile: https://github.com/os-autoinst/openQA/issues/4795

I understand the upstream containers can't satisfy all use cases, but this has almost no effect on image size -- `docker images` reports 1.37GB before and after my change, and being able to use the upstream containers directly is helpful for our rather under-resourced effort to run OpenQA tests directly at https://gitlab.gnome.org/GNOME/gnome-build-meta/

**Comment by Martchus** [comment]
The link to the PR is actually https://github.com/os-autoinst/openQA/pull/4804.

Sorry for not having it merged by now. We normally require two approvals but apparently haven't the capacity right now.

@os-autoinst/tools-team Somebody cares to review the mentioned PR?

**Comment by ssssam** [comment]
Some extra step seems to be needed to roll out the change to the Dockerfile - see https://github.com/os-autoinst/openQA/pull/4804#issuecomment-1270281657
