### ISSUE TITLE
Questionable dependencies: perl(YAML), perl(IO::Socket::INET6), perl(IO::Socket::SSL)

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#507]
these three are listed in cpanfile and in the spec file in OBS, but I can't find a reason for any of them to be required by openQA. The IO ones I'm not so sure about (I guess maybe they're needed to establish connections even if the code doesn't explicitly use them?), but YAML at least seems bogus.

**Comment by AdamWill** [comment]
on the other hand, t_requires probably needs to have `perl(Perl::Critic)` added, as needed by `lib/perlcritic/Perl/Critic/Policy/HashKeyQuotes.pm` - it was added to `cpanfile` but not to the RPM spec.

**Comment by okurz** [comment]
You should be able to adjust the cpanfile as you like, provide a PR and travis should tell if it misses anything as it uses the cpanfile.

**Comment by kraih** [comment]
IO::Socket::SSL is required for TLS support in Mojolicious (not sure if that is currently being used in openQA), but IO::Socket::INET6 should definitely be avoided. A long long time ago it was required for IPv6 support, but has since been replaced with IO::Socket::IP.

**Comment by coolo** [comment]
perl::critic is off as it's a too heavy dependency for too little gain. The policy is only used when you call the perlcritic target - which travis does for you. YAML is already gone. 

That leaves Socket::INET6 - this came from the spec file. So removing it there first

**Comment by coolo** [comment]
they were removed some time ago
