### ISSUE TITLE
os-autoinst/consoles/VNC.pm

### ISSUE THREAD

**Issue by MalloZup** [os-autoinst/openQA#510]
How to reproduce:

QEMU-Version: 
-----------------------------
Repository: openSUSE-Leap-42.1-Update
Name: qemu
Version: 2.3.1-9.1
Arch: x86_64
=========

job runned on locally, System: openSUSE-LEAP..
Repos are  standart from openqa Leap.
URI             : http://download.opensuse.org/repositories/devel:/openQA/openSUSE_Leap_42.1/

openqa: up-to-date
Job posted on the web-interface : OK

When running the web-int, (or isotovideo ), i got the message:

DIE Undefined subroutine &tinycv::new_vncinfo called at /usr/lib/os-autoinst/consoles/VNC.pm line 919.

So nowhere i founded the def of function. I looked in past commits, this function wasn't there, last valid commit : 
7d7ea0b99c3148f909046c670b2dc37abca2d16f,
then she was introduced.

No test runs, os-autoinst stop with sigterm to qemu. If i don't reset back to valid commit, i can't run tests.

For further details i can paste more logs.

**Comment by okurz** [comment]
tinycv was changed and you need to recompile it to get it to work when you are using a local working copy of isotovideo. Are you sure you are not using a local isotovideo? Call
```
make -C ppmclibs
```
from `os-autoinst` root

**Comment by coolo** [comment]
you must have some local files conflicting with your packages.

**Comment by okurz** [comment]
Reproduced together with @MalloZup
```
/usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi/auto/tinycv/tinycv.so
```
was not owned by package `os-autoinst` but a leftover from a local `make install`. Yes @MalloZup shouldn't have done it but `zypper in os-autoinst` also does not complain when checking for file-conflicts and IMHO it should.

**Comment by coolo** [comment]
and what file is owned by os-autoinst?

**Comment by okurz** [comment]
the one I mentioned

**Comment by coolo** [comment]
but you said "was not owned by package os-autoinst" - so what? if it's owned by os-autoinst package, a zypper up will overwrite the file.

**Comment by okurz** [comment]
I think it didn't. Nevermind, IMHO it's not worth our time to try to reproduce it.
