### ISSUE TITLE
Error when registering a worker when `base_url` has trailing `/`

### ISSUE THREAD

**Issue by sdclarke** [os-autoinst/openQA#5115]
After [this commit](https://github.com/os-autoinst/openQA/commit/48e25e5daaa1aafd12065dcaa59c9efa3695eb38) if the Web UI config has the `base_url` set to an address with a trailing `/` (e.g. http://1.2.3.4/), a worker will fail to register to it as the HMAC calculation done by the server will have an extra '/' character prepended to the input string.

**Comment by Martchus** [comment]
Should be fixed by https://github.com/os-autoinst/openQA/pull/5131.
