### ISSUE TITLE
gru's "infinite repeat on failure" design is awful

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#519]
So, yeah, I really hate how Gru is set up to work when a task fails.

It just leaves it in the queue and loops back around. So until a higher priority task appears, it just tries the failed task over and over again. If the failure isn't transient, it'll just keep failing over and over and over and over. It never goes to sleep. It never decides "this just isn't working out" and puts the task off to the side and warns the admin or anything. Nope. It just loops around eternally, failing again and again and again. When a higher priority task appears it'll do that, but then go right back to looping on the broken task. Lower priority tasks will _never_ get run until the failing task is cleared out somehow.

I would like to fix this; I hope I'll get some spare time to work on it. Here is my initial idea: the Gru task schema should get a new column, 'failure_count' or somesuch. It's an integer. Every time Gru ran a task and it failed, it would increment the integer. Gru's search for 'what task should I do next' should exclude tasks whose failure_count is higher than, say, 5. There would be a page or something in the admin interface which listed tasks in this state and let you manually reset their failure count to get them run again (so you could figure out what was wrong with them). Maybe Gru would have a one-time code block which searched for all tasks with failure_count > 5 and logged their IDs on startup (as just another place where the admin could notice broken tasks).

Thoughts?

**Comment by coolo** [comment]
From delayed_job gem documentation (that we use in OBS):

> On error, the job is scheduled again in 5 seconds + N ** 4, where N is the number of attempts.

**Comment by AdamWill** [comment]
yeah, some kind of back-off factor would be another option - I was thinking something like that combined with a gradual lowering of the priority till it's only ever being run very occasionally and if nothing else is waiting?

**Comment by kraih** [comment]
In Minion this is handled by storing two values with every job, 1) the number of times a job has been retried, and 2) the number of times a job is allowed to be retried. And then a delay is generated with a configurable backoff factor `(retries ** 4) + 15` (15, 16, 31, 96, 271, 640...) whenever a job fails. http://mojolicious.org/perldoc/Minion#backoff

**Comment by coolo** [comment]
Translated into https://progress.opensuse.org/issues/18462
