### ISSUE TITLE
Anonymous user is not allowed to get the pubkey which was needed in Dockerfile

### ISSUE THREAD

**Issue by wnereiz** [os-autoinst/openQA#524]
Currently the anonymous user can not get pubkey where is at https://build.opensuse.org/source/devel:openQA/_pubkey , this will lead following Dockerfile to failed to import pubkey and add necessary repositories:
* openQA/docker/webui/Dockerfile
* openQA/docker/worker/Dockerfile

**Comment by coolo** [comment]
the correct path is https://api.opensuse.org/public/source/devel:openQA/_pubkey

**Comment by wnereiz** [comment]
Thanks! I will update the Dockerfile.
