### ISSUE TITLE
Feature Request: Install Oauth2 Plugin By Default in Containers

### ISSUE THREAD

**Issue by davidmhewitt** [os-autoinst/openQA#5266]
Is there a reason why the `perl(Mojolicious::Plugin::OAuth2)` package isn't installed by default in the webui containers? 

I've just tried to deploy OpenQA with some config for Github auth and found that the pre-built containers from the repository quit on startup due to this missing plugin. Meaning I can't use the Helm charts or container deployment methods as documented in the installation guide in the README without rolling my own Dockerfiles and containers.

**Comment by Martchus** [comment]
I guess the reason is just that we currently don't use it ourselves. I suppose including one more Perl module isn't a big deal. All Dockerfiles are managed in Git so I suppose you're only a PR away from having that :-)

**Comment by davidmhewitt** [comment]
@Martchus Thanks for confirming, I'd be happy to open a PR to resolve this.

Does it make sense to add this to `dependencies.yaml` so it's picked up as a dependency of the RPM? Or is just the Dockerfile fine?

**Comment by okurz** [comment]
Hm, always a hard decision to make. I assume the module wouldn't introduce any critical additional dependencies or maintenance implications so we could just pull it in through the rpm file but it's bad practice to pull in dependencies that are not necessarily needed. Same would apply for the containers but on a lower level. We could provide additional container variants. That would be more expensive build server wise but provide more fine grained choices for you and other users. How about that?

**Comment by Martchus** [comment]
I would not create a new container variant for such a small dependency. If we start creating new variants like that we will end up with tons of containers. I'd say if someone wants a tailored/minimal Installation for their needs they have to install from packages or build there own container. Our container should cover common use cases and Oauth2 is one in my opinion (even though we don't use it ourselves at the moment).

**Comment by okurz** [comment]
> Our container should cover common use cases and Oauth2 is one in my opinion (even though we don't use it ourselves at the moment).

So put it in rpm then
