### ISSUE TITLE
TAP with Open vSwitch

### ISSUE THREAD

**Issue by Vogtinator** [os-autoinst/openQA#527]
The section "TAP with Open vSwitch" on the networking documentation does not seem to work as described.
Apart from being slightly misleading (even with ovs tunctl is still needed), there are two issues that should be mentioned:

- At least on Leap 42.1, workers started by systemd fail with a "Permission denied" message for tapX. Launching them manually with "sudo -u _openqa-worker ..." works.
- Before the tapX interfaces can be used by QEMU, they need to be up: "ip link set tap0 up"

And last but not least: As the tapX interfaces are tagged, the traffic reaching br0 is tagged as well.
This means that routing won't work as described, as br0 needs to be on the same VLAN.

**Comment by nadvornik** [comment]
The section "TAP with Open vSwitch" is an extension to "TAP based network". That means that you still have to create TAPs and set their owner to _openqa-worker. Then the workers start fine, at least for me.

Yes, the traffic on br0 is tagged, but there are openflow rules for special handling of IP 10.0.2.2. Packets with this IP are redirected to br0 untagged. This is enough for reaching os-autoinst http server or external network if 10.0.2.2 is configured as gateway.
See https://github.com/os-autoinst/os-autoinst/blob/master/os-autoinst-openvswitch for details.

I am not sure about "ip link set tap0 up", for me it works without it.

**Comment by Vogtinator** [comment]
> The section "TAP with Open vSwitch" is an extension to "TAP based network". That means that you still have to create TAPs and set their owner to _openqa-worker.

I know, but it's still misleading.

> Yes, the traffic on br0 is tagged, but there are openflow rules for special handling of IP 10.0.2.2. Packets with this IP are redirected to br0 untagged. This is enough for reaching os-autoinst http server or external network if 10.0.2.2 is configured as gateway.
> See https://github.com/os-autoinst/os-autoinst/blob/master/os-autoinst-openvswitch for details.

It did not work for me. I ran tcpdump on br0 and only saw tagged packets. Any idea how to debug this?

> I am not sure about "ip link set tap0 up", for me it works without it.

Another leap 42.1-specific issue?

**Comment by nadvornik** [comment]
Configure the VM machine with static IP 10.0.2.15/24 and then ping 10.0.2.2
I am using wireshark but it is probably the same with tcpdump.
On tapX you should see original packets, on br0 untagged packets with source IP rewritten to 10.1.X.Y range.

ovs-ofctl dump-flows br0 should show rules added to table 1, together with packet counters.

**Comment by Vogtinator** [comment]
This didn't seem to be the case for me, but it might've been something else. Due to the issue with systemd I had to play around with the setup for a while, I might've broken something.
Currently I switched over to VDE networking, but I'll try OVS again.

**Comment by MalloZup** [comment]
isn't a LEAP special issue.
tap worked fine for me. you have to add the apparmor profile check. i used leap 42.1 and i had no special issue with systemd or anything else. 

Vladmir , one question. In the code for TAP device, you have to pass the MACADRESS to not encounter the udev "eth1" problem. In normal cases, you don't add the Mac-adress :*** 123456, backend do this automatically for you. is there any special case, why i don't add this, and you have to add this manually via variable?. Just a report/question. cheers.

**Comment by nadvornik** [comment]
I think that in most cases you want to use the the MAC assigned by the backend.
Any hardcoded MAC can cause conflicts if there are multiple tests generated from the same template.

**Comment by MalloZup** [comment]
nadvornik, the openqa backend use/set hardcoded MAC, because the udev rules 70 they use expect this mac adress. This is because they want to don't modify the original image, i think.

see backend/qemu.pm : (line 312) 
 $vars->{NICMAC}   ||= "52:54:00:12:34:56" if $vars->{NICTYPE} eq 'user';

with tap devices, the backend/qemu.pm doesn't set this MAC. if i don't pass this MAC (via jobpost or json file), this MAC is expected from udev-rules. i got a "broken" eth0. and instead udev give me a eth1.

@Vogtinator : have you tried to pass the MAC "52:54:00:12:34:56" and see on openqa image wich eth dev you have.

**Comment by Vogtinator** [comment]
@MalloZup I completely removed openvswitch from the system and I'm currently happy with VDE. I can test that in a few weeks though.

**Comment by MalloZup** [comment]
ok cool thx, for me it fixed the issues, and i think that's the problem

**Comment by Vogtinator** [comment]
I'll close this one for now and reopen if it still doesn't work after the apparmor update and the MAC.
