### ISSUE TITLE
CASEDIR shown in the job's settings should have a working URL

### ISSUE THREAD

**Issue by ricardobranco777** [os-autoinst/openQA#5272]
For example, if I have `CASEDIR=https://github.com/ricardobranco777/os-autoinst-distri-opensuse#rmt` the link should point to the right branch like `https://github.com/ricardobranco777/os-autoinst-distri-opensuse/tree/rmt`.

**Comment by kalikiana** [comment]
What link are you referring to? Do you have an example of a job, or maybe a screenshot?

**Comment by okurz** [comment]
If you specify `CASEDIR=foo_bar#invalid` then openQA settings should have exactly that setting regardless if openQA will be successful in executing a job like that for better error analysis. The finally evaluated value will be in the vars.json file that is uploaded as part of the job. Is that acceptable for you as a solution?

**Comment by ricardobranco777** [comment]
> If you specify `CASEDIR=foo_bar#invalid` then openQA settings should have exactly that setting regardless if openQA will be successful in executing a job like that for better error analysis. The finally evaluated value will be in the vars.json file that is uploaded as part of the job. Is that acceptable for you as a solution?

Yes.  I will fix my clone script to use a clickable CASEDIR.  Thanks!
