### ISSUE TITLE
"Waiting for input" stuck on rotating gear after clicking on "rerun last step" in interactive mode

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/openQA#533]
When creating needles in interactive mode, after you return from needles editor and click on rerun button, it shows rotating gear and doesn't refresh back to previous button - you have to wait until waiting for needle times out. See for example [this video](https://youtu.be/mK0VLErT0f4?t=30).

**Comment by okurz** [comment]
since the issue was filed a lot has changed in layout, design and also the implementation of the interactive mode. Does this still happen? If not, please close the issue.

**Comment by garretraziel** [comment]
It looks like it has been fixed. I'll reopen it in case I encounter it again.
