### ISSUE TITLE
favicon is SUSE-specific

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#536]
A Fedora person pointed out to me that the openQA favicon is the openSUSE geeko. Perhaps we could make the favicon part of the 'branded' bits, and/or get a distro-neutral logo and favicon made by a friendly design team?

**Comment by coolo** [comment]
If you have a friendly design team at hand, go ahead. Ours is fine with the logo ;)

**Comment by AdamWill** [comment]
well as it happens I do, they might try and sneak a fedora logo in there though ;)

**Comment by sysrich** [comment]
The chameleon wearing a fedora would be funny to see

More seriously, our design guys have been kicking around ideas for a neutral logo, but nothing ready to kick around and discuss and they dont have time to actively work on it at the moment

**Comment by AdamWill** [comment]
I can ask our design folks if they're willing to come up with something.

**Comment by AdamWill** [comment]
@tflink said we should get Debian involved, then the geeko could have a fedora and a beard...

**Comment by AdamWill** [comment]
So our designers have come up with some proposals here:

https://fedorahosted.org/design-team/ticket/437

it'd be great to have your opinions! If you don't want to sign up for FAS, just reply here and I'll make sure the comments get passed along.

**Comment by sysrich** [comment]
I will probably sign up for FAS and comment there but not before I go to sleep, so some thoughts already

1. I really like the ideas so far, certainly not one of those cases of "OMG I HATE IT, BURN IT WITH FIRE"
2. The 'd' does kind of look like a 'd' to me also. I would like it to took more like an 'a'
3. I really like how your designer clearly read our https://opensuse.github.io/branding-guidelines/ and picked colours to match
4. I think number '7' is best for a FAVICON (I have a thing for green ;))

Now, further thoughts, moving on from a FAVICON to a 'logo'
5. I do not think number '7' is best for a general openQA logo, and would prefer one of the 'coloured ext options'
6. While I love Green, I do like the idea of the logo really embracing the fact that openQA isn't just an openSUSE project, so I prefer the options that blend well with the 'traditional identities' (Green for SUSE, Blue for Fedora) of our respective projects. Therefore I lean towards number '2' as my favourite of the options for a general openQA logo. Or maybe we can find a version that takes our Green for the Q and one of your blues for the A?
7. or maybe as I'm now talking about a 'logo' not a FAVICON, we do something in the FAVICON font that actually says 'openQA' in the _logo_?

**Comment by coolo** [comment]
I think it's not cool to move from SUSE specific to something specific to SUSE+Fedora. So I would prefer something that looks good without having to tell messages in colours. So I would stick with 7 - I guess other distributions can live with some green in the UI :)

**Comment by aaannz** [comment]
I can't relate to those icons. Call me stupid, but I simply don't understand them.
To look at them as symbols, they are too much like letters, but as a letters Q is backwards and a is like d.
I don't want to diminish any work done, I just doesn't understand the idea behind it.

**Comment by coolo** [comment]
Favicons are seldomly brilliant art. Google's is just a G, so having a Q+A for openqa is already double the price. Remember it's 16x16 - there isn't much space for a story.

**Comment by okurz** [comment]
agreed, having *any* favicon that clearly differs from what we currently have 
(the same as for many other opensuse/suse services) would help me a lot to 
differentiate browser tabs :-) So +1 for choice 7, maybe round courners :-)
after the favicon we can come up with a logo, after that, rediscuss the 
favicon as necessary (will be 2018 by then).

**Comment by garretraziel** [comment]
Logos were updated here https://fedorahosted.org/design-team/ticket/437#comment:14, what do you think?

**Comment by sysrich** [comment]
Concept 1, box and no box, both get a +1 from me
Like the colour, the A is clearly an A..works for me

**Comment by coolo** [comment]
Then I go with no box - Jan, please make a PR and let's close the topic :)

**Comment by garretraziel** [comment]
AdamWill will do it, I have a PTO 😊

**Comment by mairin** [comment]
I'll ask Mary to prep #1 without the box for you guys.

**Comment by okurz** [comment]
That would be great. BTW a preliminary version is already live on openqa.opensuse.org :-)

**Comment by AdamWill** [comment]
I saw all the changes on git master recently...I'll try and get Fedora's packages and deployments updated in the next week or two. @mairin , I think the SUSE guys were also looking for SVGs....

**Comment by AdamWill** [comment]
I've asked on the trac tickets for the SVGs, hopefully we'll get those soon, sorry for the delay! I'm also updating Fedora's production openQA today so we'll all look the same with the new icon =)

**Comment by coolo** [comment]
https://github.com/os-autoinst/openQA/pull/776

**Comment by AdamWill** [comment]
is the issue of the icon at top-left of the web UI being fuzzy (because it's lower resolution) fixed yet?

**Comment by coolo** [comment]
the so called branding icon is a svg containing the 16x16 icon as "svg" upscale. Now that we have the svg proper it will scale itself.
