### ISSUE TITLE
Add Apparmor in the doc for TAP

### ISSUE THREAD

**Issue by MalloZup** [os-autoinst/openQA#544]
Following the documentation for TAP, Networking in OpenQA,

you could encounter the following issue : 

QEMU: qemu-system-x86_64: -netdev tap,id=qanet0,ifname=tap0,script=no,downscript=no: could not open /dev/net/tun: Permission denied

This is caused 1 for the  owner of tun/tap dev ( this  is well documented in the doc, so OK)
Not documented is follow:
2: apparmor could block. 
so  we have to add in the doc:

vim /etc/apparmor.d/usr.share.openqa.script.worker
+  /dev/net/tun rw,

systemctl restart apparmor.service

**Comment by Vogtinator** [comment]
Had the same issue. The apparmor profile is part of this repo so it can be fixed here instead of being mentioned in the doc.
