### ISSUE TITLE
Do database init / upgrade in openQA, not RPM spec

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#555]
Currently, both openSUSE and Fedora have database init / upgrade happening in RPM `%post`. I kinda don't like this; it doesn't really 'belong' to packaging. In my opinion openQA itself should do this.

I'm willing to work on this, but I wanted to file a ticket first to get other folks' thoughts on whether it's a good idea and if so how/where to do it. My initial thought was to put it into `connect_db` in `Schema.pm` (or make it a separate sub which `connect_db` calls).

The `initdb` / `upgradedb` scripts would still exist for the purpose of doing `--prepare_init` / `--prepare_upgrades`, but `init_database` and `upgrade_database` would be done in openQA itself.

Thoughts? Thanks!

**Comment by aaannz** [comment]
This can solve the issue with running old code with new database schema. I tend to like this. `Schema.pm` is IMO good place.

**Comment by AdamWill** [comment]
one concern I have is there's various options in the scripts - I'm thinking particularly of `--force` and `--from_uninitialized_database` - which I don't think could really work inside openQA. I'm not sure if those are really needed, though, I haven't looked into why they exist.

**Comment by aaannz** [comment]
I assume you don't want to remove original functionality from the scripts. So in case openQA will fail to start due to upgrade/init problem one can still revert to original way.

**Comment by AdamWill** [comment]
eh, I guess. It would be neater not to duplicate, but if we need it we can keep it.

**Comment by aaannz** [comment]
See https://github.com/os-autoinst/openQA/pull/574

**Comment by AdamWill** [comment]
I think we can close this now, right? thanks for the work!

**Comment by coolo** [comment]
well, @aaannz still needs to adapt our spec file I'd think
