### ISSUE TITLE
Every '#'-reference links to test if it's unknown

### ISSUE THREAD

**Issue by Soulofdestiny** [os-autoinst/openQA#604]
So we have a implemented redirect for 'poo#' and 'bsc#' tags in comments that are linking to progress.opensuse.org and bugzilla, and also a t# for a link to a specific test.

I've tried to use 'gh#' for a github pull request, but this was also link to a test, which most likely doesn't exist.

I would suggest to disable links for unknown tags (and implement a 'gh#' for github ;))

![screenshot from 2016-03-09 15-15-11](https://cloud.githubusercontent.com/assets/3983634/13637871/ea2554c4-e609-11e5-9196-1db4d6439cef.png)

**Comment by Soulofdestiny** [comment]
just came to my mind that you can refer to either to pull requests for tests and/or for backend... so maybe we should just look into "os-autoinst-distri-opensuse" for now...

**Comment by coolo** [comment]
openQA is a generic project - having a link from gh# to opensuse tests without any config option or whatsoever is not going to sync in.

**Comment by Soulofdestiny** [comment]
Then it's even easier, isn't it?

**Comment by okurz** [comment]
https://github.com/os-autoinst/openQA/pull/973 adds generic github bugref markers. Also, unknown tags are ignored. please close.
