### ISSUE TITLE
emit count or list of remaining jobs with `job_done` signal?

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#609]
so I'm not sure if you want to do this or not, thus filing as an issue not a PR.

For the fedmsg plugin I wrote, I did this:

```
# find count of pending jobs for the same build
# this is so we can tell when all tests for a build are done
my $build = $app->db->resultset('Jobs')->find({'id' => $event_data->{id}})->settings_hash->{BUILD};
$event_data->{remaining} = $app->db->resultset('Jobs')->search(
    {
        'settings.key'   => 'BUILD',
        'settings.value' => $build,
        'state'          => [OpenQA::Schema::Result::Jobs::PENDING_STATES],
    },
    {join => qw/settings/})->count;
```

i.e. I took the raw event and added another property to the data, which is a count of remaining jobs for the same build that are in one of the `PENDING_STATES`.

The _reason_ for this is so you can tell when all tests for a build are done: when you get a message with the `remaining` value 0. (For my purposes it could just as well be a boolean, but meh, emitting the count was easy).

I wondered if this might be useful to others, in which case we could do it at the point of sending the original event - at least for `job_done` and any other event for which it might make sense?

(Now I think about it I should probably also add a `build` property to the message, for my needs...)

**Comment by aaannz** [comment]
Seems like a good idea, but we'll merge after #521. After I add job_settings indices there ( see https://github.com/os-autoinst/openQA/pull/534#issuecomment-179852912 ).

**Comment by coolo** [comment]
I don't know if this was done - if it wasn't, either do a PR or a progress.oo ticket
