### ISSUE TITLE
`jobs/[job_id]` endpoint gives less information than `jobs?ids=[job_id]` for no obvious reason

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#648]
The 'softfail' state seems to be really only visible via the web UI. Compare: [web UI 'softfailed' test](https://openqa.stg.fedoraproject.org/tests/13333), [API 'softfailed' test](https://openqa.stg.fedoraproject.org/api/v1/jobs/13333) - note our staging deployment is running close to git master. In the UI the overall state shows as 'passed' but you can clearly see the soft failed test. From the API result there is absolutely no indication that the test soft failed, AFAICS the API data is entirely indistinguishable from a regular 'passed' job.

In general, I guess, the API could stand to expose more information on the test steps in the job.

**Comment by okurz** [comment]
agreed. "softfail" is more like an additional property of a job in state "passed", not a state by itself

**Comment by AdamWill** [comment]
Interestingly, after further poking I realized this only applies to *this particular API endpoint* - i.e. `jobs/[job_id]` . If you instead use `jobs?ids=[job_id]` you get more info, including the result for each test step, thus you *can* determine whether the test soft failed with this endpoint.

That's actually perfectly sufficient for me as all our real code (inc. openqa-python-client) actually uses the latter endpoint, not the former. So I don't actually need this to be fixed. But if you like we can leave it open to cover the fact that `jobs/[job_id]` differs from (and omits information compared to) `jobs?ids=[job_id]` , since that feels like a bug rather than a feature...

**Comment by coolo** [comment]
No, leave it open. We need to have softfail as final result. There are too many places in the code that loops the modules.

**Comment by coolo** [comment]
this is done
