### ISSUE TITLE
usr/share/openqa/script/client  doesn't not accept full-path in a variable

### ISSUE THREAD

**Issue by MalloZup** [os-autoinst/openQA#650]
## How to reproduce

```
/usr/share/openqa/script/client --params example.json jobs post
```

with 

```
 "HDD_1" : "/var/lib/openqa/share/factory/hdd/MY-IMAGE.mg",
 "ISO" : "/var/lib/openqa/share/factory/iso/MY_ISO_EXAMPLE.iso",
```

the workaround is to set only  

```
HDD_1 :"MY-IMAGE.img"  ...
```
## Why is needed:

When adding new testscases to existing one, as test-developer i do a clonejob from the existing one.

Since sometimes a new variable for control the the tests as to be added,  i have to modify the vars.json file that the clone.job has made for me on the web-api.

This vars.json contain mixed values, from engine log and testing work-flow itself.

So the issue, is a sub-issue of the vars.json problem. But could be fixed as first.

**Comment by sysrich** [comment]
But HDD images must always be in `/var/lib/openqa/share/factory/hdd/` and ISO images must always be in `/var/lib/openqa/share/factory/iso/`

So why is this an issue?

**Comment by MalloZup** [comment]
the issues is as i reported.

with  /usr/share/openqa/script/client --params example.json jobs post

when you make HDD = " var/lib/openqa/share/factory/hdd/myHDD.qcow2", it doesn't work jobs post.

you have to manually remove the full-path

**Comment by sysrich** [comment]
And how does the incorrect parameters end up in that `json` file in the first place?

**Comment by MalloZup** [comment]
this end-up, when you are trying to make a clonejob for an existing tests.
[ if you mean first place as line number, well this was an example ]

Ok , clonejob work nice, you have the upstream-test locally.
But assuming you want to modify some variable from the json-file, because you have to modify this scenario, then you have to copy manually the vars.json and remove/debug the incorrect  [for testing-workflow] values, and try to debug it. In these, there is this s/HDD= full-path/relative error

**Comment by coolo** [comment]
Dario is assuming that a vars.json can be used 1:1 as params.json

**Comment by MalloZup** [comment]
i don't mind to use a file like as test.json additionaly to the vars.json, if for the backend logging is  the vars.json important.

Or what it could be interesting, is that the clonejob script could copy a * "tester" .json file in the local directory or somewhere, so a tester can easy retrieve the right values for modify a scenario.

**Comment by okurz** [comment]
I propose to rewrite the `vars.json` with semi-automatic rewrites, e.g. using `sed` if this is desired. I don't see where client needs to be extended. I recommend to close this.
