### ISSUE TITLE
Single quote in setting of one testsuite in openqa webui, make all settings of that testuite missing

### ISSUE THREAD

**Issue by alice-suse** [os-autoinst/openQA#666]
Severity: high

Description:
 single quote in setting of one testsuite, make all settings of that testuite missing.
 double quote will become missing when edit again

**Comment by okurz** [comment]
If a single quote destroys the content I would suggest to add an input validator before the content is accepted. This should be implemented in the code handling the testsuite settings.

**Comment by nilxam** [comment]
I've poke this issue a bit, basically hashedparams can not handle ``a single quote`` from the formdata, https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/WebAPI/Plugin/HashedParams.pm#L40

for example,
```$VAR1 = '{settings}{ABC} = \'\'CBA\';';```

**Comment by aaannz** [comment]
funny thing, there is this eval. If you use value like this `Q';open(my $q,'>','/tmp/TEST2');print 'X` it will create that file ;)
Ladies and gentleman, we have a breach here.

**Comment by aaannz** [comment]
Fortunately you need to be openQA admin to do that, but still.

**Comment by nilxam** [comment]
forget to reminding that, the value with double quote was missing looks like about how to handle it in input value field, I guess ``<input value=""VALUE"/>`` or ``<input value="\"VALUE"/>`` both won't work.

**Comment by aaannz** [comment]
fixed by merged PRs
