### ISSUE TITLE
symlinked test/needles repository does not work anymore since #613

### ISSUE THREAD

**Issue by okurz** [os-autoinst/openQA#667]
I don't see why this is needed. It prevents me from using a repo for needles and symlink it into the testcasedir. Why use `Cwd::realpath` here?

@rajcze could you comment?

**Comment by okurz** [comment]
seems like #669 did not fix every case, e.g. within the needle editor the needles can not be selected although switching through needle candidates works.

**Comment by rajcze** [comment]
Sorry for the late reply, the "realpath" was added in response to "...make sure that only data from the $NEEDLEDIR can be read..." request. But using some Perl equivalent of Python's `abspath` might be equally good solution for that requirement, and at the same time solve the symlink issue

**Comment by aaannz** [comment]
JFYI: @okurz already fixed that by using `File::Spec->rel2abs` which doesn't expand links (see https://github.com/os-autoinst/openQA/pull/671).

**Comment by okurz** [comment]
works for me with #671
