### ISSUE TITLE
Test suite settings should take priority over settings passed by POST

### ISSUE THREAD

**Issue by garretraziel** [os-autoinst/openQA#684]
Fedora for ARM is distributed not by installation ISO, but by already preinstalled disk image. When I want to schedule our ARM tests, I'm doing so while setting `HDD_1_URL`, but not `ISO`. I have one test that boots from this disk, creates user/sets password with our "initial-setup" utility and then saves disk by setting `STORE_HDD_1`. Then I have another ARM test where I want to use that saved disk, but I cannot, because `HDD_1` set on test gets overwritten by parameter passed during test scheduling.

I tried to overcome this by setting `HDD_ARM=http://url/to/hdd` during POST, `HDD_1_URL=%HDD_ARM%` on first test and correctly setting `HDD_1` on second test, but `_URL` gets resolved only for parameters set by POST (so `HDD_1` wasn't created and disk wasn't downloaded). I also tried to set `ASSET_1_URL=http://url/to/hdd` during POST, `HDD_1=%ASSET_1%` on first test and correctly setting `HDD_1` on second test and that almost worked (`ASSET_1` was created and disk was downloaded), but then disk was placed in `other/` directory, not in `hdd/` directory (so it couldn't find it).

I cannot come up with mean how to solve this problem (resolving `_URL` for all parameters would be enough), but I think that parameters set on specific test should take precedence before "generic" parameters passed during POST for all tests.

Rationale is that when I'm passing parameters that are the same for all tests planned by one POST, I should be able to override parameters for specific tests.

**Comment by aaannz** [comment]
I am against this. I think POST requests should have priority. Not everyone has write access to test suites so if someone is developing a test and want to experiment with different settings she must use API call.

Now you have a point, that when there is a dependent test it doesn't make sense to override its variables. So one solution would be to add this logic to iso controller.

**Comment by aaannz** [comment]
The number of disks os-autoinst prepares depends on NUMDISKS variable. So theoretically you can use HDD_2_URL in POST and set HDD_1=%HDD_2% in test suite settings for the parent job and keep the child job as is.
When NUMDISKS is not set or set to 1 it should ignore HDD_2, but scheduler will download it as HDD asset anyway. If it works and you decides to use this, document it somewhere or in half a year it will have a WTF sticker.

**Comment by garretraziel** [comment]
That's true. Other solution would be to create some variable like "NOT_OVERWRITE=HDD_1". I will try your solution on Monday.

**Comment by coolo** [comment]
+1 for leaving the priority as it is.

**Comment by sysrich** [comment]
+1 for leaving the prio as it is

**Comment by garretraziel** [comment]
So using `HDD_2` but leaving `NUMDISK=1` works, but it's rather hack-y. I still think that not overwriting specifically `HDD` for consecutive tests is better idea.

**Comment by aaannz** [comment]
It is hacky, true.
There are already some ideas flying around about template inheritance/inclusion which will require some work on how scheduler interprets test variables so I think we can add something like variable names prefixes i.e. `+HDD_1` to signalize this variable should not be overwritten. This way it will work for any variable and will not require introducing any new special variable.
