### ISSUE TITLE
Need needle update for aarch64

### ISSUE THREAD

**Issue by dirkmueller** [os-autoinst/openQA#693]
https://openqa.opensuse.org/tests/201766/modules/yast2_bootloader/steps/7

**Comment by okurz** [comment]
Fixed by https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/72

**Comment by okurz** [comment]
@coolo, @dirkmueller please close

**Comment by dirkmueller** [comment]
Lgtm, Thanks!
