### ISSUE TITLE
needle diff mockup

### ISSUE THREAD

**Issue by coolo** [os-autoinst/openQA#707]
We have multiple problems in the needle diff as it is. Mostly the fact that we blend images over each other gives the wrong impression we would compare full screens and not areas. So IMO we should have 2 mode - one improved area comparision and one full screen view.

To improve the area comparision I have this mockup, perhaps this is better than what we have.
![mock](https://cloud.githubusercontent.com/assets/1067203/15801776/1a386aa4-2aa0-11e6-867e-50c78a6c0e0b.png)

Next to this would be a full screen comparision not marking areas at all.

**Comment by coolo** [comment]
the labels will be challening on small needles, so I would need to only show the one of them if the area is smaller than X pixels.

**Comment by coolo** [comment]
there is one small detail wrong in my mockup - the right part should be green as it's the 100% match.

Anyway, my prototype is reachable (for those with SUSE VPN) at http://gertrude:3000/tests/346493 - the flickering is a bit annoying, but not flickering would be very noisy. I'm torn

**Comment by okurz** [comment]
looks nice. To me it feels a bit sluggish and slow to move the bar, you mean that by "flickering"?

**Comment by coolo** [comment]
no, the flickering is about the text going in and out. The needle diff surely didn't get faster by grayscaling :(

**Comment by okurz** [comment]
I don't see the flickering so it is also not annoying me :-) About the performance, it is annoying. Sometimes the bar even gets "stuck" and takes some mouse moving around until it reacts again. A checkbox to enable this new advanced, more performance hungry mode would be fine, though. Otherwise I prefer to leave as is

**Comment by coolo** [comment]
you're using firefox? it works splendid in chromium, but I've seen Ludwig suffering from poor performance in firefox

**Comment by okurz** [comment]
yes, firefox.

**Comment by Vogtinator** [comment]
Before the rework got merges, it was possible for anonymous and unprevileged logged-in users to have a look at the full screenshot of needles.

I can't find a way to do that on openqa.opensuse.org anymore.

**Comment by coolo** [comment]
Yes, that's why I put "Next to this would be a full screen comparision not marking areas at all." as part of the functionality.

**Comment by okurz** [comment]
fixed by #711, please close

**Comment by coolo** [comment]
no. we still need the fullscreen comparision - that's why I wanted to have @asdil12's changes in to work on top of that

**Comment by okurz** [comment]
still open? then maybe poke @asdil12

**Comment by coolo** [comment]
the changes referenced are in.

**Comment by coolo** [comment]
Moved the remains to https://progress.opensuse.org/issues/18460
