### ISSUE TITLE
unable to login with unicode chars in 'firstname' , 'lastname' fields in openid

### ISSUE THREAD

**Issue by mimi1vx** [os-autoinst/openQA#72]
I try to log to http://openqa.opensuse.org with my opensuse openid account 'mimi.vx' 
as result i get rainbow vomiting raptor with horn...

Full back url:

https://openqa.opensuse.org//response?oic.time=1415959398-60a2c43c53c9f3c50ace&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.op_endpoint=https%3A%2F%2Fwww.opensuse.org%2Fopenid%2Fprovider&openid.claimed_id=https%3A%2F%2Fwww.opensuse.org%2Fopenid%2Fuser%2Fmimi_vx&openid.response_nonce=2014-11-14T10%3A03%3A31Z0&openid.mode=id_res&openid.identity=https%3A%2F%2Fwww.opensuse.org%2Fopenid%2Fuser%2Fmimi_vx&openid.return_to=https%3A%2F%2Fopenqa.opensuse.org%2F%2Fresponse%3Foic.time%3D1415959398-60a2c43c53c9f3c50ace&openid.assoc_handle=1408580992698-3628&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cns.ext2%2Cext1.email%2Cext1.fullname%2Cext2.mode%2Cext2.type.email%2Cext2.value.email%2Cext2.type.fullname%2Cext2.value.fullname%2Cext2.type.nickname%2Cext2.value.nickname%2Cext2.type.firstname%2Cext2.value.firstname%2Cext2.type.lastname%2Cext2.value.lastname&openid.sig=3ZxLuRj8lz2Z5T9N3p2iJOzWry3D5kLoprgUD7bFYNM%3D&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.ext1.email=mimi.vx%40gmail.com&openid.ext1.fullname=Ond%C5%99ej+S%C3%BAkup&openid.ns.ext2=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext2.mode=fetch_response&openid.ext2.type.email=http%3A%2F%2Fschema.openid.net%2Fcontact%2Femail&openid.ext2.value.email=mimi.vx%40gmail.com&openid.ext2.type.fullname=http%3A%2F%2Faxschema.org%2FnamePerson&openid.ext2.value.fullname=Ond%C5%99ej+S%C3%BAkup&openid.ext2.type.nickname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffriendly&openid.ext2.value.nickname=mimi_vx&openid.ext2.type.firstname=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext2.value.firstname=Ond%C5%99ej&openid.ext2.type.lastname=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ext2.value.lastname=S%C3%BAkup

**Comment by choldrim** [comment]
I got the same..  ;(
Is any solution of it now ?

**Comment by garretraziel** [comment]
I'm not sure whether it's the same problem, but none of us could log in using Fedora's openid. It gives us:

    no_identity_server: Could not determine ID provider from URL.

on the main page after trying to log in. But if I use SUSE's server, it works.

**Comment by aaannz** [comment]
Problem with unicode was 'naive_verify_failed_return'. And was in perl-Net-OpenID-Consumer package. I already reported it upstream with a proposed fix ( https://rt.cpan.org/Public/Bug/Display.html?id=106930 ). openSUSE packages are building already with that patch applied.
Your problem seems different, I assume you are using openID URL as stated in you dockerfile? I'll take a look at it.

**Comment by garretraziel** [comment]
Yes, I am using `https://id.fedoraproject.org/` as a provider.

**Comment by aaannz** [comment]
Sorry, I can't reproduce it. I created fedora account, attached my openid instance to fedora's openID, logged in and all went through.

**Comment by garretraziel** [comment]
Have you tried it with Docker setup? Although I don't think that it's caused by Docker (because SUSE's server works with Docker). And also, one of us was hitting this for a long time, but it started happening with our other accounts also. Perhaps it's caused by Fedora infrastructure.

**Comment by aaannz** [comment]
Now I checked through docker and it works for me. So I would blame your infra :) 
When pulling image from docker I assume it already contain updated dockerfile, right? Just to be sure I'm testing the right thing.

**Comment by garretraziel** [comment]
No, we are planning to push it to Docker hub once it works without a problem. You have to build it by yourself with Dockerfiles from my pull request. I can build it for you and push it somewhere into Hub if you want.

**Comment by aaannz** [comment]
No, it's ok. At least I'll learn another thing about docker ;)
Anyway, openQA side is IMO cleared, so either it's docker changes or your infra. Or just random config typo.

**Comment by garretraziel** [comment]
I've tested it and it's actually problem with our infra here at Red Hat. Running it from outside and trying to connect to it works without problem. So the problem isn't in openQA.

**Comment by aaannz** [comment]
Good. I believe this issue can be closed.
