### ISSUE TITLE
coveralls can not show source from github

### ISSUE THREAD

**Issue by okurz** [os-autoinst/openQA#721]
## observation

error message on https://coveralls.io/builds/6513395/source?filename=lib%2FOpenQA%2FScheduler%2FScheduler.pm: "The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API. "
## steps to reproduce

go to https://coveralls.io/builds/6513395/source?filename=lib%2FOpenQA%2FScheduler%2FScheduler.pm or try to display any source file from a coveralls build and observe the error message
## problem

see error message
## suggestion

see error message

**Comment by aaannz** [comment]
I can't help with this one or don't know how. As soon as I log in I can see all the individual lines and I can't find any setting leading to fix this for anonymous users. Maybe @coolo if he's coveralls repo owner.

**Comment by coolo** [comment]
sometimes it does, sometimes it doesn't
