### ISSUE TITLE
Experimental keys on scalar is now forbidden at template admin/workers/index.html.ep line 26

### ISSUE THREAD

**Issue by mnowaksuse** [os-autoinst/openQA#742]
With recent openQA (openQA-4.3.1465806453.7bb19aa-157.1.noarch) on Tumbleweed I am unable to access `/admin` page. I get `404` with vomiting `unicornis rex` and this in journal:
```
openqa[1383]: [Tue Jun 14 11:18:27 2016] [1572:error] Experimental keys on scalar is now forbidden at template admin/workers/index.html.ep line 26.
openqa[1383]: 21:                     <th>connected</th>
openqa[1383]: 22:                     <th>current step</th>
openqa[1383]: 23:                 </tr>
openqa[1383]: 24:             </thead>
openqa[1383]: 25:             <tbody>
openqa[1383]: 26:                 % for my $workername (sort keys $workers) {
openqa[1383]: 27:                     %   my $worker = $workers->{$workername};
openqa[1383]: 28:                     <tr id="worker_<%= $worker->{id} %>" >
openqa[1383]: 29:                         <td class="worker">
openqa[1383]: 30:                             %= link_to( $workername => url_for('admin_worker_show', worker_id => $worker->{id}) )
openqa[1383]: 31:                         </td>
```

**Comment by mnowaksuse** [comment]
Also links `stop` and `restart` in job point to `404` and terminate nothing.

**Comment by dgutu-suse** [comment]
@okurz, @coolo told me yesterday on IRC that it's your fault :) is it?

**Comment by okurz** [comment]
if you take a look at who last changed the code, yes it was me. Problem here is that I don't have a Tumbleweed for easy testing available right now. https://github.com/os-autoinst/openQA/pull/740 was done to help with that, i.e. fixing the issue in line 26. But as it looks there are also problems somewhere later. I think it shouldn't be that hard to fix. Could you do it yourself? I am happy to help with setting up an openQA development environment for you.

**Comment by coolo** [comment]
it's fixed
