### ISSUE TITLE
Test overview has weird state "None:"

### ISSUE THREAD

**Issue by Vogtinator** [os-autoinst/openQA#757]
The test overview shows a row:

```
Passed: 28 Soft Failure: 11 Failed: 51 None: 1
```

What is `None` supposed to mean? There is already `Unknown`. It looks like canceled tests fall into that category.

**Comment by coolo** [comment]
None is most likely unfinished

**Comment by coolo** [comment]
please move this over to progress.oo if it's any important. we plan work there
