### ISSUE TITLE
Expiration date format does not match the expected one on Chromium

### ISSUE THREAD

**Issue by hwoarang** [os-autoinst/openQA#770]
Hi

Please see attached screenshots. The first one is from chromium, the latter is from Firefox.

![apikeyscreate](https://cloud.githubusercontent.com/assets/45309/16582710/8a56e1d8-42a8-11e6-8289-1c84a54641d8.png)

![apikeyscreate2](https://cloud.githubusercontent.com/assets/45309/16582796/39776d4a-42a9-11e6-92b7-6da7e9e21578.png)

As you see, in the chromium case I am prompted for a ```mm/dd/yyyy``` format for the expiration date of the API key, but this is being rejected since it does not match the expected ```?^a:^\d{4}-\d{2}-\d{2}(?: \d{2}:\d{2}(?::\d{2})?)?$)``` format. I am unable to use the recommended format, because chromium forces the ```mm/dd/yyyy --:-- --``` in that field. I can't simply delete these and add whatever I want there.

However this does not happen on Firefox, which does not force a particular date format.

This is a brand new installation on TW using the following guide

https://github.com/os-autoinst/openQA/blob/master/docs/Installing.asciidoc

and using the ```Fake``` authentication mechanism

The openQA installation is on a VM and I am accessing the web interface from the host.

**Comment by okurz** [comment]
that is something I have never seen as I am working with firefox. You can actually open a calendar widget if you click on the small downwards pointing arrow but it only fills in the date, not the time or the timezone marker so I don't think one can actually enter a valid expiration date on chrome/chromium. Adding a key without expiration date works, however.
