### ISSUE TITLE
Toggling interactive mode, stepping forward etc. from 'Live View' tab sends you back to 'Details' tab

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#774]
With a current git snapshot of openQA, it seems like all the action buttons on the 'Live View' tab - like the interactive mode toggle and the interactive mode actions, all the ones whose apparent URL is `https://[server]/tests/[job_id]#` - work, but flip you over to the 'Details' view, and you have to switch back to 'Live View' manually. Or at least that's what happens on Firefox.

**Comment by coolo** [comment]
@okurz - I told you master is buggy :)

https://github.com/os-autoinst/openQA/pull/767/commits/3a5f6a703ad1ccf96a78364215fbdb3f44da07db

**Comment by okurz** [comment]
yes, but … I told you first fix, then rework ;-)

**Comment by AdamWill** [comment]
REWRITE IT ALL IN RUST IMMEDIATELY

**Comment by AdamWill** [comment]
also https://github.com/os-autoinst/openQA/pull/767/commits/ea4c359d7ca11bd14aa0f1de2274ccfefb12cf22 , right?

**Comment by AdamWill** [comment]
Fix confirmed. I've applied both https://github.com/os-autoinst/openQA/pull/767 and https://github.com/os-autoinst/os-autoinst/pull/524 to Fedora's staging instance since they fix several bugs that were annoying me, we'll see how it shakes out in a few days of use.
