### ISSUE TITLE
Screenshot in needle editor view is too large at 1080x1920

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#780]
This is the exact opposite problem to https://github.com/os-autoinst/openQA/issues/764 ; at my weird 1080x1920 resolution, it seems the screenshot shown in the needle editor view is too _large_ :) This seems to happen both on our prod instance (which is running git a08377c) and our staging instance (which is running git c34c90b with #767 applied).

![screenshot](https://www.happyassassin.net/temp/needlelarge.png)

**Comment by coolo** [comment]
what happens if you trigger a resize forth and back?

**Comment by AdamWill** [comment]
Is [https://www.happyassassin.net/temp/needleeditresize.webm](this) what you wanted to see?

**Comment by coolo** [comment]
it seems not to resize at all

**Comment by coolo** [comment]
ok, I can reproduce on will

**Comment by coolo** [comment]
now that it's most interesting. it works in development mode, but fails in production

**Comment by coolo** [comment]
Actually not - the production system still runs f16f2fd - which doesn't contain the fix for #764

**Comment by coolo** [comment]
So no, I can't reproduce it neither with firefox nor chromium. Can you please check the javascript console if you see something fishy there?

**Comment by coolo** [comment]
doesn't seem to be so important
