### ISSUE TITLE
Installation failure on openSUSE Leap 42.1

### ISSUE THREAD

**Issue by XGWang0** [os-autoinst/openQA#832]
Installation env:
Host : openSUSE Leap 42.1
openQA:4.4.1471438621.334731f-143.2
perl-Mojolicious:7.01-109.1
perl-Mojolicious-Plugin-AssetPack:1.17-2.1
perl-Mojolicious-Plugin-RenderFile:0.10-11.1

Installation steps:
1. add repos
#zypper ar -f obs://devel:openQA/openSUSE_Leap_42.1 openQA
#zypper ar -f obs://devel:openQA:Leap:42.1/openSUSE_Leap_42.1 openQA-perl-modules
2.Install openqa
#zypper in openqa
#zypper in os-autoinst
3.Start webui server
#systemctl start openqa-webui
4.Webui status
#linux-49xs:/var/lib/openqa # systemctl status openqa-webui -l
openqa-webui.service - The openQA web UI
   Loaded: loaded (/usr/lib/systemd/system/openqa-webui.service; disabled)
   Active: failed (Result: exit-code) since Thu 2016-08-18 06:32:39 EDT; 25s ago
  Process: 22333 ExecStart=/usr/share/openqa/script/openqa prefork -m production --proxy -i 100 -H 400 -w 10 (code=exited, status=13)
 Main PID: 22333 (code=exited, status=13)

Aug 18 06:32:39 linux-49xs openqa[22333]: Mojo::Asset::File::__ANON__('Mojo::Asset::File=HASH(0x53ca350)') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojo/Base.pm line 43
Aug 18 06:32:39 linux-49xs openqa[22333]: Mojo::Base::__ANON__('Mojo::Asset::File=HASH(0x53ca350)') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojo/Asset/File.pm line 125
Aug 18 06:32:39 linux-49xs openqa[22333]: Mojo::Asset::File::slurp('Mojo::Asset::File=HASH(0x53ca350)') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious/Plugin/AssetPack.pm line 169
Aug 18 06:32:39 linux-49xs openqa[22333]: Mojolicious::Plugin::AssetPack::_process_from_def('Mojolicious::Plugin::AssetPack=HASH(0x35c8ee8)', undef) called at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious/Plugin/AssetPack.pm line 62
Aug 18 06:32:39 linux-49xs openqa[22333]: Mojolicious::Plugin::AssetPack::process('Mojolicious::Plugin::AssetPack=HASH(0x35c8ee8)') called at /usr/share/openqa/script/../lib/OpenQA/WebAPI.pm line 211
Aug 18 06:32:39 linux-49xs openqa[22333]: OpenQA::WebAPI::startup('OpenQA::WebAPI=HASH(0x17ccf70)') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious.pm line 168
Aug 18 06:32:39 linux-49xs openqa[22333]: Mojolicious::new('OpenQA::WebAPI') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojo/Server.pm line 17
Aug 18 06:32:39 linux-49xs openqa[22333]: Mojo::Server::build_app('Mojo::Server=HASH(0x16c2f38)', 'OpenQA::WebAPI') called at /usr/lib/perl5/vendor_perl/5.18.2/Mojolicious/Commands.pm line 72
Aug 18 06:32:39 linux-49xs openqa[22333]: Mojolicious::Commands::start_app('Mojolicious::Commands', 'OpenQA::WebAPI') called at /usr/share/openqa/script/../lib/OpenQA/WebAPI.pm line 525
Aug 18 06:32:39 linux-49xs openqa[22333]: OpenQA::WebAPI::run() called at /usr/share/openqa/script/openqa line 35

Consequence:
I do not know which step is wrong, is it a bug for this version of openqa?

**Comment by XGWang0** [comment]
This is complete logs : http://paste.suse.de/19205

**Comment by aaannz** [comment]
Try to call `./script/generate-packed-assets` from /usr/share/openqa There was probably some problem generating assets. @coolo will know more once he is around.

**Comment by XGWang0** [comment]
There is no generate-packed-assets file under  /usr/share/openqa/script   
I lost some primary packages?

**Comment by nilxam** [comment]
Not really, it basically is used during compilation so we don't ship it in the binary file, you can found it in github.

**Comment by aaannz** [comment]
Ah that's right! We no longer generate them during installation, I forgot. Given this is permission problem, check that everyone has read access to /usr/share/openqa/assets/assetpack.def and assetpack.db

**Comment by XGWang0** [comment]
It is so weird , openqa works now. I only stop "apparmor".  But I try to restart "apparmor" and can not reproduce above launching issue. I am not sure whether "running apparmor" is the root reason for that.
However , still thanks aannz and nilxam.

**Comment by aaannz** [comment]
Apparmor again, how could I forgot about that?
openQA installs new apparmor rules so apparmor needs to be restarted and we don't do it automatically during package install.

Closing.

**Comment by XGWang0** [comment]
I think it should be a issue, it will take very bad experience to user and is hard to position error, i think it can be fixed on .spec file, whether we have the plan for that?
