### ISSUE TITLE
iso file to place in "share/factory/iso" or "factory/iso" what correct path ?

### ISSUE THREAD

**Issue by michelmno** [os-autoinst/openQA#847]
In the adding-a-new-iso-to-test paragraph (1) there are two sentences about placement of iso file name that are not same path.
 What is the valid information ? 

(1) https://github.com/os-autoinst/openQA/blob/master/docs/GettingStarted.asciidoc#adding-a-new-iso-to-test
```
To start testing a new ISO put it in /var/lib/openqa/share/factory/iso
You must place the file in /var/lib/openqa/factory/iso
```

**Comment by coolo** [comment]
/var/lib/openqa/factory/ is a symlink to /var/lib/openqa/share/factory - so it doesn't matter. But having /var/lib/openqa/factory/ consistently everywhere would be good

**Comment by okurz** [comment]
@michelmno would you like to try and provide a PR?

**Comment by michelmno** [comment]
@coolo  in https://github.com/os-autoinst/openQA/blob/master/docs/Installing.asciidoc there is a paragraph:

It is always best to use the canonical locations, not the compatibility symlinks - so run scripts from /usr/share/openqa/script, not /var/lib/openqa/script.

So do we really want to use /var/lib/openqa/factory/ ? rather than  /var/lib/openqa/share/factory ?

**Comment by coolo** [comment]
ok, I just checked the code. I was the under impression, openQA used /var/lib/openqa/factory and we only had the share for NFS purposes. But the code uses share/factory indeed, so I merged your PR
