### ISSUE TITLE
suggestion to point to stable repo in open.qa/downloads page

### ISSUE THREAD

**Issue by michelmno** [os-autoinst/openQA#857]
may need to reconcile the default path to retrieve openQA:

in http://open.qa/downloads/ ...You can find them in the "openQA repository"
that is https://build.opensuse.org/project/show/devel:openQA

in https://github.com/os-autoinst/openQA/blob/master/docs/Installing.asciidoc
You can find openSUSE packages in OBS in the "openQA:stable repository"
that is https://build.opensuse.org/project/show/devel:openQA:stable

I guess the best one to use is the stable one.
But I do not know where is the source of the pages for http://open.qa/downloads

**Comment by okurz** [comment]
The sources are in the "gh-pages" branch, that is standard for "github pages". The file you are looking for is in
https://github.com/os-autoinst/openQA/blob/gh-pages/downloads.html

**Comment by coolo** [comment]
the stable repo is not maintained. It's outdated by now
