### ISSUE TITLE
openqa scheduler can not schedule the multi-machine job  with different "WORKER_CLASS" on ipmi worker

### ISSUE THREAD

**Issue by jerrytt** [os-autoinst/openQA#913]
I have 2 phy-machine with ipmi .
I need assign 2 ipmi-worker to 2 jobs with parallel dependence .

1. Setup 2 ipmi-worker with different  WORKER_CLASS ,(specify the ipmi to the phy-machine)
2. Add 2 test(job)  to same group with different "WORKER_CLASS";

When i trigger the job with parallel,  the dependence job can not schedule.

After use same "WORKER_CLASS" , ithis issue is gone

**Comment by coolo** [comment]
please use progress.opensuse.org to report issues. We don't need 2 places

**Comment by jerrytt** [comment]
sure , I'll take care next time.
I'll migrate this issue to progress.opensuse.org.
