### ISSUE TITLE
`limit_assets` will never clean up hard disk images from tested builds

### ISSUE THREAD

**Issue by AdamWill** [os-autoinst/openQA#928]
This could be a bit tricky to fix, but I'll file an issue first then try and think of ways to fix it.

`limit_assets` has this little condition in it:

```
        # ignore predefined images
        next if ($asset->type eq 'hdd' && $a->created_by == 0);
```

the reasoning is obvious. It's common to have some disk image assets which are kind of test fixtures; e.g. a hard disk image with some specific partition layout to test the installer can parse it properly, or an image with an old distribution release installed on it to test upgrades. Indeed we don't want openQA to decide such assets are 'old' and delete them.

However, now in Fedora we're also testing hard disk images _that are part of our distribution composes_ - ARM disk images, e.g. https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Spins/armhfp/images/Fedora-Minimal-armhfp-Rawhide-20160812.n.0-sda.raw.xz . These absolutely are just transient images under test, just like ISOs, and we want them to be trimmed by `limit_assets`.

Unfortunately I can't see an easy way to tell one from the other :/ The first thought I had is simply to establish a naming convention for images that are 'fixtures', and except images that fit the naming convention from `limit_assets`. That'd probably work, but it's also kinda dumb and prone to edge cases as more people start using openQA.

Can anyone think of a better option?

**Comment by coolo** [comment]
one option is calling asset_register with some parameter to mark it as volatile. And yes, we have the same problem - just that our jeos images are small enough not to cause a real problem :)

**Comment by AdamWill** [comment]
How would we signal that a given asset was to be marked volatile in the first place, though? Special var passed in when running jobs that marks some/all of the job's assets as volatile? Dedicated API call just for that? What were you thinking?

**Comment by AdamWill** [comment]
another option, I guess, would be to have *two* directories for each asset class, one for volatile, one for fixtures; all the code that looks for assets would have to be adjusted to check one directory then the other, and `limit_assets` could ignore the 'fixture' directories and only work on the volatile ones...

**Comment by coolo** [comment]
ok, in your case you create jobs with _URL - in this case I consider the asset to be in the hands of openQA anyway. It can clean it up - and redownload if needed.

In our case we sync both types of assets before posting the job. So in our case we would sync and then POST /asset?type=hdd&name=removeifuneeded.qcow2&volatile=1

So in case the job group is too large, we can take the volatile hdds just like isos.

**Comment by okurz** [comment]
IMHO the process should be more obvious to an outside observer so I opt to clean up everything under the directories we have and create new directories for the fixed assets which may only use but not cleanup, e.g. "fixed/" subir of each HDD/ISO/Repo dir. This way we can also instruct external Tools to take care of these assets knowing that openQA does not mangle with these. Otherwise it would again be non obvious outside the context of openQA database which are the fixed and which are the volatile assets.

**Comment by okurz** [comment]
IMHO fixed

**Comment by AdamWill** [comment]
oh yeah, I done fixed it. (i'm assuming you guys moved your fixed assets...)

**Comment by okurz** [comment]
we learned the hard way ;-)

**Comment by AdamWill** [comment]
haha, oops!
